#+file-path: ./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf
#+file: [[./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf][csa_security_guidance_v4.0_1670814714973_0.pdf]]
#+title: hls__csa_security_guidance_v4.0_1670814714973_0

* It is a disruptive technology that has the potential to enhance collaboration, agility, scaling, and availability
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7c9a-29dc-4107-9d58-27bf8108c4f8
:END:
* Cloud computing is a model for enabling ubiquitous, convenient, on-demand network access to a shared pool of configurable computing resources (e.g., networks, servers, storage, applications, and services) that can be rapidly provisioned and released with minimal management effort or service provider interaction.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7cbb-07fa-4a3d-b567-7da388a371e8
:END:
* Paradigm for enabling network access to a scalable and elastic pool of shareable physical or virtual resources with self-service provisioning and administration on-demand.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7ccf-4903-459a-b713-e8ac5b8bfa86
:END:
* The key techniques to create a cloud are abstraction and orchestration. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7db7-979f-4dac-8d15-398d035bc4fe
:END:
* This is the difference between cloud computing and traditional virtualization; virtualization abstracts resources, but it typically lacks the orchestration to pool them together and deliver them to customers on demand, instead relying on manual processes.
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dc7-d4f5-4be2-a70f-925d9a7bbc80
:END:
* Clouds are multitenant by nature. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dd3-cd94-4c5a-96e6-fba937a263b5
:END:
* Essential Characteristics
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e07-fda3-4afa-94ef-48acdf4bcb43
:END:
* ISO/IEC 17788 lists six key characteristics, the first five of which are identical to the NIST characteristics. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e49-77cb-4660-b8af-1d7a93d8aedd
:END:
* Service Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e75-d7c4-4826-ab2e-b278eb4bd862
:END:
* ISO/IEC uses a more complex definition with a cloud capabilities type that maps closely to the SPI tiers (application, infrastructure, and platform capability types). It then expands into
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e9b-312b-4c2f-aa0f-1414ed075700
:END:
* Deployment Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7eba-2f61-489b-a116-f0c25c388f59
:END:
* Reference and Architecture Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7efc-dce0-4ba7-ae66-6b46a7acbc1f
:END:
* For an in-depth reference architectural model, we again recommend ISO/IEC 17789 and NIST 500-292, which complement the NIST definition model.
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7f09-afc6-4ab4-afa1-bcfdb11dabdb
:END:
* In most cases, those APIs are both remotely accessible and wrapped into a web-based user interface. This combination is the cloud management plane, since consumers use it to manage and configure the cloud resources, such as launching virtual machines (instances) or configuring virtual networks. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 14
:hl-color: yellow
:id: 639e7f53-dbe5-46f6-a57d-75328958966c
:END:
* PaaS adds an additional layer of integration with application development frameworks, middleware capabilities, and functions such as databases, messaging, and queuing.
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7f8f-3b45-45ca-bfa5-de1fc3fe4627
:END:
* One option, frequently seen in the real world and illustrated in our model, is to build a platform on top of IaaS. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fae-98ca-4de8-834c-743ecd0ae041
:END:
* Another example is an application deployment platform. T
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fc1-7ed3-47ce-829b-147492b98752
:END:
* Thus all SaaS tends to have an application/logic layer and data storage, with an API on top. Then there are one or more presentation layers, often including web browsers, mobile applications, and public API access.
:PROPERTIES:
:ls-type: annotation
:hl-page: 17
:hl-color: yellow
:id: 639e8002-f34a-4f75-a97a-5ad01695f9ba
:END:
* Logical Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e8018-9f5c-440d-bfbd-9a72f49066d1
:END:
* The key difference between cloud and traditional computing is the metastructure. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e807a-2d0e-4107-bfaa-b0b4b3b87601
:END:
* Another key difference is that, in cloud, you tend to double up on each layer. Infrastructure, for example, includes both the infrastructure used to create the cloud as well as the virtual infrastructure used and managed by the cloud user. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e808e-2424-4d16-9b53-b9c4870ee70b
:END:
* As we will discuss later this has profound implications on who is responsible for, and manages, security. These layers tend to map to different teams, disciplines, and technologies commonly found in IT organizations.
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e80b4-cb7a-4a24-b464-21fd736c0b4d
:END:
* All the traditional security domains remain, but the nature of risks, roles and responsibilities, and implementation of controls change, often dramatically.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ac7-6ee8-44d2-896e-e51c1dde3859
:END:
* Cloud Security and Compliance Scope and Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29af5-e72f-45e8-8327-4433fb5fa2a4
:END:
* At a high level, security responsibility maps to the degree of control any given actor has over the architecture stack:
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b40-d120-417b-a73b-aa340de34ccf
:END:
* Software as a Service: The cloud provider is responsible for nearly all security,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b7f-225b-4d32-aea3-ddcb98a90cd1
:END:
* Platform as a Service: The cloud provider is responsible for the security of the platform, while the consumer is responsible for everything they implement on the platform,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b95-368a-4707-8c05-910a1ea28525
:END:
* Infrastructure as a Service: Just like PaaS, the provider is responsible for foundational security, while the cloud user is responsible for everything they build on the infrastructure.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ba6-05f5-4293-96b9-3013922048af
:END:
* The most important security consideration is knowing exactly who is responsible for what in any given cloud projec
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bba-1e34-4627-a8a6-215756eb05a9
:END:
* This shared responsibility model directly correlates to two recommendations:• Cloud providers should clearly document their internal security controls and customer security features so the cloud user can make an informed decision. Providers should also properly design and implement those controls.• Cloud users should, for any given cloud project, build a responsibilities matrix to document who is implementing which controls and how. This should also align with any necessary compliance standards.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bd3-010d-41d1-9aec-1ad16148be1c
:END:
* • The Consensus Assessments Initiative Questionnaire (CAIQ). A standard template for cloud providers to document their security and compliance controls.• The Cloud Controls Matrix (CCM), which lists cloud security controls and maps them to multiple security and compliance standards. The CCM can also be used to document security responsibilities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29be8-86e6-4006-8567-b884aa109a7c
:END:
* Cloud security models are tools to help guide security decisions. The term “model” can be used a little nebulously, so for our purposes we break out the following types:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c1b-f38e-4471-b42c-8df3cfdacbed
:END:
* The CSA has reviewed and recommends the following models:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c46-53ed-448e-a6c6-7cb9b5636042
:END:
* there is a relatively straightforward, high-level process for managing cloud security:
:PROPERTIES:
:ls-type: annotation
:hl-page: 23
:hl-color: yellow
:id: 63a29c8f-df2e-4539-8e0c-91af8c2c8fcc
:END:
* Areas of Critical Focus
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29ce0-7ce5-45db-aaaa-1215edcf59e8
:END:
* Governing in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29d46-b49e-4af6-932d-45978a15d225
:END:
* Operating in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 25
:hl-color: yellow
:id: 63a29d54-776e-49ff-87b1-ee42348e8ae2
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 26
:hl-color: yellow
:id: 63a29de6-519e-48eb-81ac-aee67895a120
:END:
* Cloud Computing Concepts and Architectures
:PROPERTIES:
:ls-type: annotation
:hl-page: 7
:hl-color: yellow
:id: 63a29e36-db21-4a2d-923a-de4c8c06d71f
:END:
* Governance and Enterprise Risk Manag
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: blue
:id: 63a29e54-a150-4ad2-ab1e-02cae87b4862
:END:
* Governance and Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29eec-7c8e-4634-8dea-e4c55708329b
:END:
* For security professionals, cloud computing impacts four areas of governance and risk management:
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29f0d-b8d0-488d-aaa7-134dba06d5c0
:END:
* In a simplified hierarchy, information security is a tool of information risk management, which is a tool of enterprise risk management, which is a tool of governance. The four are all closely related but require individual focus, processes, and tools.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f54-371d-4b06-b6d3-24a6d2760f69
:END:
* Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f8a-f999-44bc-84fd-96226fe06188
:END:
* The primary issue to remember when governing cloud computing is that an organization can never outsource responsibility for governance, even when using external providers. This is always true, cloud or not, but is useful to keep in mind when navigating cloud computing’s concepts of shared responsibility models.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fa0-1b79-4142-8913-c0f3057216a6
:END:
* Cloud computing changes the responsibilities and mechanisms for implementing and managing governance. Responsibilities and mechanisms for governance are defined in the contract, as with Security Guidance v4.0 © Copyright 2021, Cloud Security Alliance. All rights reserved29 any business relationship
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fbb-8a95-4f89-99fb-0e12dda74092
:END:
* Tools of Cloud Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 29
:hl-color: yellow
:id: 63a29fd4-49dd-4566-9361-cab7fad8a7bb
:END:
* Assessments and audits should be based on existing standards (of which there are many). It’s critical to understand the scope, not just the standard used. Standards like the SSAE 16 have a defined scope, which includes both what is assessed (e.g. which of the provider’s services) as well as which controls are assessed
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a012-aeba-4f22-9a3c-7980e990b296
:END:
* Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a023-1d31-4335-92c2-a605eb24c9f7
:END:
* As with governance, the contract defines the roles and responsibilities for risk management between a cloud provider and a cloud customer. And, as with governance, you can never outsource your overall responsibility and accountability for risk management to an external provider.
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a045-f77e-4ebc-b3e4-93740df604a1
:END:
* Risk management in cloud is based on the shared responsibilities model (which we most often discuss in reference to security). The cloud provider accepts some responsibility for certain risks, and the cloud customer is responsible for anything beyond that. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a053-92a8-4472-af6b-85fe5309fa95
:END:
* Whereas governance is nearly exclusively focused on contracts, risk management can delve deeper into the technology and process capabilities of the provider, based on their documentation. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a07f-9ed1-4bb8-86eb-e1d638712195
:END:
* Risk tolerance is the amount of risk that the leadership and stakeholders of an organization are willing to accept.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a08b-1226-4d09-a32a-6f9f162dd304
:END:
* The Effects of Service Model and Deployment Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0a3-308f-45ca-9d7b-e02a0a873252
:END:
* In the majority of cases, SaaS presents the most critical example of the need for a negotiated contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0d9-ea14-4208-b0d0-9a99f88e68d2
:END:
* The likelihood of a fully negotiated contract is likely lower here than with either of the other service models. That’s because the core driver for most PaaS is to deliver a single capability with very high efficiency.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0f6-9783-4a39-b8ae-a982eef5f9c3
:END:
* Infrastructure as a Service represents the closest that Cloud comes to a traditional data center (or even a traditional outsourced managed data center), and the good news is that the vast majority of existing governance and risk management activities that organizations have already built and utilize are directly transferable. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a10f-8940-40d3-b2c6-f820b5561dc0
:END:
* Cloud customers have a reduced ability to govern operations in a public cloud since the provider is responsible for the management and governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a132-0dec-4914-96f7-9de2e4e70dc3
:END:
* The customers also often have reduced ability to negotiate contracts, which impacts how they extend their governance model into the cloud. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a144-c648-44ea-92ed-f9d5e48bd65a
:END:
* Public cloud isn’t the only model that impacts governance; even private cloud will have an effect. If an organization allows a third party to own and/or manage the private cloud (which is very common), this is similar to how governance affects any outsourced provider. There will be shared responsibilities with obligations that are defined in the contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a166-70c9-4a72-8b15-d99620ad842b
:END:
* When contemplating hybrid cloud environments, the governance strategy must consider the minimum common set of controls comprised of the Cloud Service Provider’s contract and the organization’s internal governance agreements. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a17f-8685-4935-a7f8-7bb804fa7cec
:END:
* Since community clouds are a shared platform with multiple organizations, but are not public, governance extends to the relationships with those members of the community, not just the provider and the customer. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a191-efd7-47ef-b305-abffda14a70b
:END:
* Cloud Risk Management Trade-Offs
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a1ab-b475-448a-b3cc-741045aacc81
:END:
* Cloud Risk Management Tools
:PROPERTIES:
:ls-type: annotation
:hl-page: 34
:hl-color: yellow
:id: 63a2a202-5b49-42a5-9dbc-79fb500d399c
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 35
:hl-color: yellow
:id: 63a2a23e-a885-460f-bc1a-0bf868508b55
:END:
* Legal Issues, Contracts and Electronic Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2ca-c1ab-41fb-908d-fa743bb1c83d
:END:
* Legal Frameworks Governing Data Protection and Privacy
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2e4-4fdf-45d2-8281-0cb967daf59f
:END:
* Under these laws, the data controller (typically the entity that has the primary relationship with an individual) is prohibited from collecting and processing personal data unless certain criteria are met. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a301-9c85-496b-9687-a99e5411b8b2
:END:
* the controller may collect and process data, according to the consent agreement. These laws define numerous obligations, such as confidentiality and security obligations, for the entities that access personal data. When entrusting a third party to process data on its behalf (a data processor), a data controller remains responsible for the collection and processing of that data. The data controller is required to ensure that any such third parties take adequate technical and organizational security measures to safeguard the data.
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a31e-34f1-40fb-9601-6beb0ab55d0e
:END:
* In many cases, the laws of different countries might apply concurrently, in accordance with the following:
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a32d-6cfa-4d76-a702-c408d1414549
:END:
* Required Security Measures
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b758-8649-4f1a-b6b9-1e0a4650a2a7
:END:
* Restrictions to Cross-border Data Transfers
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b769-9c6f-4125-b27d-a9cca2f884da
:END:
* Many countries prohibit or restrict the transfer of information out of their borders. In most cases, the transfer is permitted only if the country to which the data is transferred offers an“adequate level of protection” 
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b792-ead3-49f6-8be9-8158174c1f8a
:END:
* Alternatively, the data importer and exporter may need to sign a contract ensuring the maintenance of privacy rights for data subjects.
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b7a1-3a59-46e0-929e-5d17f746f558
:END:
* Regional Examples
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7b8-ca71-44c4-9ca0-2fe5d32ea64c
:END:
* he Privacy Act of 1988 (Privacy Act) 
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7d8-613b-4921-83c9-cbdf97bef50b
:END:
* Australian Consumer Law (ACL). 
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7ed-e2fb-4d51-88ad-f10b3297c139
:END:
* May 2017, proposed Measures on the Security of Cross-Border Transfers of Personal Information and Important Data were published by the Chinese government and are currently being evaluated for potential implementation
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b812-45ad-4aef-bc29-f9c462be1daf
:END:
* 2017 Cyber Security Law
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b81e-d4f3-4fd1-8671-7059d9358bae
:END:
* The Cyber Security Law imposes a series of security obligations to operators of critical information infrastructure, including internal organization, training, data backup; emergency response requirements, security inspections and annual assessments of cyber security risks; and reporting to relevant authorities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b846-9077-4006-89ce-fdf7020be514
:END:
* During the second quarter of 2017, China issued Draft Regulations on Cross Border Data Transfers to supplement the Cyber Security Law. These regulations would go beyond the working of the Cyber Security Law, and expand its scope.
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b855-01c1-4de1-8285-6efd80399564
:END:
* Act on the Protection of Personal Information (APPI
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b86a-c23c-4f3e-a510-cef1fd6628fd
:END:
* Profession-specific laws, such as the Medical Practitioners’ Act; the Act on Public Health Nurses, Midwives and Nurses; and the Pharmacist Act, require registered health professionals to maintain the confidentiality of patient information
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b884-be4d-411d-bb50-1051627a2bc0
:END:
* September 2017, amendments to the APPI law will limit the ability to transfer personal data to third parties, with prior consent of the data subject generally being required to transfer data to a third party
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b890-ea8d-4e60-b3e5-7e920a5872bb
:END:
* the most important aspect of the Russian legal framework regarding the handling of personal information is its data localization law. Since September 2015, companies are required to store personal data of Russian citizens within Russia
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8c49e-2f8b-49ea-a9f8-8c02aaf9ed01
:END:
* Roskomnadzor, the Russian Data Protection regulator, has commenced enforcement of the law and has already blocked access to one foreign social network, which did not have a physical presence in Russia, but operated a Russian language version of its website
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8c4b0-2abe-47ee-8117-2d502260bcfa
:END:
* The European Union (EU) adopted the General Data Protection Regulation (GDPR) in 2016, which is binding on all EU member states, as well as members of the European Economic Area (EEA). The GDPR will become enforceable as of May 25, 2018. On that date, Directive 95/46/EC on the Protection of Personal Data, which had been the legal basis of the provisions of the national data protection laws of all EU and EEA member states, will be repealed.
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4c8-8695-41b1-b9a8-6a24b5cfd9cd
:END:
* important document governing aspects of the protection of personal data in the EU/EEA is Directive 2002/58/EC on Privacy and Electronic Communications
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4d7-31c0-4ccd-b441-6f1f728d05c0
:END:
* the Network Information Security Directive (NIS Directive) is paving the way to more stringent security requirements. Adopted in 2016, the NIS Directive requires EU/EEA member states to implement new information security laws for the protection of critical infrastructure and essential services by May 2018
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4e8-ccb8-4592-b42c-44d04de46bdf
:END:
* General Data Protection Regulation (GDPR)
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4f4-37ac-4cc8-a89c-750a07105e65
:END:
* Network Information Security Directive (NIS Directive)
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8c500-0a69-4f05-b87b-086488e4527a
:END:
* he NIS Directive establishes a framework to enable networks and information systems to resist, at a given level of confidence, actions that compromise the availability, authenticity, integrity, or confidentiality of stored, transmitted, or processed data, or the related services that are offered by or accessible through those networks and information systems
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8e0a2-2a84-48aa-a162-594a7316e0fd
:END:
* The requirements to be implemented into national laws include the following:
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8e0ca-342c-4277-a253-bfec3b1f8f56
:END:
* Due to its sectoral approach, the United States has hundreds of federal, state and local regulations,
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e111-087f-4347-b687-f8e01817bfde
:END:
* extensive requirements under Massachusetts’“Standards for the Protection of Personal Information of Residents of the Commonwealth,” 
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e15b-9fa0-44e6-b266-901daa86af5a
:END:
* a small number of state laws reference other specific standards (such as the Payment Card Industry Data Security Standard, PCI-DSS
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e16b-fe82-46f6-a53f-9b47b62d6f48
:END:
* Contracts and Provider Selection
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e1bd-661c-47e4-aaa5-aad06fdac86e
:END:
* Even if a specific activity is not regulated, cloud customers may have a contractual obligation to protect the personal information of their own clients, contacts or employees
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e229-7a43-46c5-bd84-3beeb6444f6c
:END:
* This obligation may stem, for example, from the Terms and Conditions and Privacy Statement
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e237-fe1d-4f32-9a69-746e4ea86453
:END:
* It is therefore prudent, and may be required by law or regulation, that the data custodian and the cloud provider enter into a formal written agreement that clearly defines the roles, the expectations of the parties, and the allocation of the many responsibilities that are attached to the data at stake.
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e25e-1b73-4383-b7f0-2a4a625d3781
:END:
* Internal Due Diligence
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e269-6a9c-4d57-a8e4-1110d2a7e51f
:END:
* Before entering into a cloud computing arrangement, both the cloud service vendor and the cloud customer should evaluate respective practices, needs and restrictions to identify relevant legal barriers and compliance requirements.
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e2c2-53fa-4607-8b3f-6faae86aaabf
:END:
* If the company, or potential cloud customer, has signed a confidentiality agreement to protect personal information or trade secrets, this agreement probably prohibits hiring a subcontractor without prior permission of the data owner. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e2d9-d025-445f-9fe1-afa4732f63c0
:END:
* Monitoring, Testing, and Updating
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e2fc-418e-4db5-8e78-f768051b2b08
:END:
* External Due Diligence
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e30f-5ff9-4995-8ee1-8e35612672f6
:END:
* Thus, depending on the nature of the proposed project, the due diligence may involve evaluating the nature and completeness of the services provided, the reputation for quality or stability of the service, the availability of a certain level of support or maintenance, the responsiveness of customer service, the speed of the network, and the location of the data centers.
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e336-43bb-441a-ba1c-0870bd32e852
:END:
* Reviewing all terms and conditions of the cloud services agreement (including all annexes, schedules and appendices) is good due diligence for any new project.
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e34f-1950-4589-af05-f0ff06ca6677
:END:
* Contract Negotiations
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e35b-3fb0-48a2-b750-fa6020f26160
:END:
* Reliance on Third-Party Audits and Attestations
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e650-a41c-4dd3-9d86-32cd259a9554
:END:
* In cloud computing, third-party audits and attestations are frequently used to assure compliance with aspects of the cloud provider’s infrastructure, allowing a customer to build their own compliant services on top of the cloud platform.
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e666-a395-4369-b2d2-5ee0d7b7e49c
:END:
* Electronic Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e67f-94d8-414d-bbf8-1194689d87c2
:END:
* In recent years, many litigants have deleted, lost or modified evidence that was detrimental to their case. In these cases, the Federal Rules of Civil Procedure allow, among other penalties, money to be awarded to the side not responsible for the destruction; 
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e69b-899a-4d52-a083-fb001d479e1c
:END:
* Possession, Custody and Control
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6b0-a9aa-4b05-8dff-8f34992d917c
:END:
* Relevant Cloud Applications and Environment
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6c6-e4d8-4d1b-9386-baea091eaf6a
:END:
* Searchability and E-Discovery Tools
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6d7-51ed-44cf-939f-6e0ee3397848
:END:
* Preservation
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6f6-477c-4e85-a269-d43b4dfd6e74
:END:
* European Union, information preservation is governed under Directive 2006/24/EC of the European Parliament and of the Council of 15 March 2006.
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e719-6bb3-4d37-a7a2-84bd4c9525b4
:END:
* Japan, South Korea and Singapore have similar data protection initiatives. In South America, Brazil and Argentina have the Azeredo Bill and the Argentina Data Retention Law of2004, Law No. 25.873, respectively.
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e722-e67c-42f7-8429-f649d25cd2dc
:END:
* Data Retention Laws and Record Keeping Obligations
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e72e-45bc-4967-b2c0-df5d100c8097
:END:
* Costs and Storage: Preservation can require that large volumes of data be retained for extended periods. Customers should consider these questions and determine the risk tolerated before moving to the cloud:
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e746-7f00-4ed3-b008-89d77fcdf4e6
:END:
* Collection
:PROPERTIES:
:ls-type: annotation
:hl-page: 51
:hl-color: yellow
:id: 63a8e773-7fc1-46cb-8ad5-d50f41d1f48e
:END:
* Because of the potential lack of administrative control a client has over its data in the cloud, collection from the cloud can be more difficult, more time-consuming and more expensive than from behind a client’s firewall. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 51
:hl-color: yellow
:id: 63a8e78e-c397-4e71-aa7e-6b6bf377d388
:END:
* Direct Access
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e860-27bd-4376-a9be-d97c2f8c665e
:END:
* Native Production
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e879-5d37-4a64-87e9-8b23078956b2
:END:
* Authenticatio
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e890-a679-475c-aec9-cf61678e5434
:END:
* Cooperation Between Provider and Client in E-Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e8a6-b2ca-4218-a617-fff05075c1dd
:END:
* Response to a Subpoena or Search Warrant
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e8c2-9745-42e2-86d1-9f186f753087
:END:
* More Information
:PROPERTIES:
:ls-type: annotation
:hl-page: 53
:hl-color: yellow
:id: 63a8e8f9-f71a-4a6d-9d96-c37fbafc6789
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 53
:hl-color: yellow
:id: 63a8e90e-85b9-4d11-b23e-458cd5fe1252
:END:
* Compliance and Audit Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 54
:hl-color: yellow
:id: 63a8e927-8c29-4f59-a7a1-d6dbe32cb126
:END:
* Understanding the interaction of cloud computing and the regulatory environment is a key component of any cloud strategy.
:PROPERTIES:
:ls-type: annotation
:hl-page: 54
:hl-color: yellow
:id: 63b30007-d186-4df7-9e2e-7634c7f85cd5
:END:
* Overview
:PROPERTIES:
:ls-type: annotation
:hl-page: 55
:hl-color: yellow
:id: 63b3002f-ac23-47c3-b149-1a8ac1ebb46d
:END:
* Compliance validates awareness of and adherence to corporate obligations 
:PROPERTIES:
:ls-type: annotation
:hl-page: 55
:hl-color: yellow
:id: 63b3003d-896a-4108-8c49-c4bda828c5f4
:END:
* Audits are a key tool for proving (or disproving) compliance
:PROPERTIES:
:ls-type: annotation
:hl-page: 55
:hl-color: yellow
:id: 63b30047-f617-4618-b64a-71e43a3f7663
:END:
* the customer is always ultimately responsible for their own compliance. These responsibilities are defined through contracts, audits/assessments, and specifics of the compliance requirements.
:PROPERTIES:
:ls-type: annotation
:hl-page: 55
:hl-color: yellow
:id: 63b30087-288c-49c9-8c6a-b90afea165de
:END:
* A pass-through audit is a form of compliance inheritance. In this model all or some of the cloud provider’s infrastructure and services undergo an audit to a compliance standard. The provider takes responsibility for the costs and maintenance of these certifications. Provider audits, including pass-through audits, need to be understood within their limitations
:PROPERTIES:
:ls-type: annotation
:hl-page: 56
:hl-color: yellow
:id: 63b300af-a09c-4cdf-a423-65636866eae1
:END:
* Cloud compliance issues aren’t merely limited to pass-through audits; the nature of cloud also creates additional differentiators.
:PROPERTIES:
:ls-type: annotation
:hl-page: 57
:hl-color: yellow
:id: 63b300cc-d1f6-4c2f-ba78-7bae089710d5
:END:
* Audits must be independently conducted and should be robustly designed to reflect best practice, appropriate resources, and tested protocols and standards.
:PROPERTIES:
:ls-type: annotation
:hl-page: 57
:hl-color: yellow
:id: 63b300f3-eea4-43f1-bdc7-c52a179b318d
:END:
* Reporting needs to include a compliance determination, as well as a list of identified issues, risks, and remediation recommendations. Audits and assessments aren’t limited to information security, but those related to information security typically focus on evaluating the effectiveness of security management and controls.
:PROPERTIES:
:ls-type: annotation
:hl-page: 57
:hl-color: yellow
:id: 63b3010d-83bf-4845-8155-a8be50cbf598
:END:
* the nature of cloud computing and contracts with cloud providers will often preclude things like on-premises audits.
:PROPERTIES:
:ls-type: annotation
:hl-page: 57
:hl-color: yellow
:id: 63b3013e-9ec9-4ce1-b70f-169b86134d4b
:END:
* Customers working with these providers will have to rely more on third-party attestations rather than audits they perform themselves. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 58
:hl-color: yellow
:id: 63b3014e-022b-477f-a551-c6998f49845b
:END:
* Cloud providers should understand that customers still need assurance that the provider meets their contractual and regulatory obligations, and should thus provide rigorous third-party attestations to prove they meet their obligations, especially when the provider does not allow direct customer assessments. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 58
:hl-color: yellow
:id: 63b30167-e8a2-4489-af3b-61ad47b9e55f
:END:
* It’s important to remember that attestations and certifications are point-in-time activities. An attestation is a statement of an “over a period of time” assessment and may not be valid at any future point. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 58
:hl-color: yellow
:id: 63b30181-6167-497d-b097-4efbb70353d2
:END:
* Some standards, such as SSAE 16, attest that documented controls work as designed/required. The standard doesn’t necessarily define the scope of controls, so both are needed to perform a full evaluation
:PROPERTIES:
:ls-type: annotation
:hl-page: 58
:hl-color: yellow
:id: 63b30199-633e-4250-9dc0-890d87d07e48
:END:
* Compliance, audit, and assurance should be continuous.
:PROPERTIES:
:ls-type: annotation
:hl-page: 59
:hl-color: yellow
:id: 63b301bc-0b28-49e9-8b66-d7ae29d311e2
:END:
* Cloud providers should:
:PROPERTIES:
:ls-type: annotation
:hl-page: 59
:hl-color: yellow
:id: 63b30200-0a31-4d81-803e-4faf3f194463
:END:
* Cloud customers should:
:PROPERTIES:
:ls-type: annotation
:hl-page: 59
:hl-color: yellow
:id: 63b30246-7246-414d-8838-7499a49e492c
:END:
* Information Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 60
:hl-color: yellow
:id: 63b3028b-6c4c-4c8a-9906-5e10b724e65a
:END:
* Ensuring the use of data and information complies with organizational policies, standards and strategy — including regulatory, contractual, and business objectives.
:PROPERTIES:
:ls-type: annotation
:hl-page: 60
:hl-color: yellow
:id: 63b302a1-2545-4d01-b131-bd5549b8e32d
:END:
* 5.1.1 Cloud Information Governance Domains
:PROPERTIES:
:ls-type: annotation
:hl-page: 62
:hl-color: yellow
:id: 63b3032d-5682-4d5b-a59e-e5a0b1a8d5bc
:END:
* The Data Security Lifecycle
:PROPERTIES:
:ls-type: annotation
:hl-page: 62
:hl-color: yellow
:id: 63b3036d-1240-488d-a8fc-b05f5f1f7fe1
:END:
* Although Information Lifecycle Management is a fairly mature field, it doesn’t map well to the needs of security professionals. The Data Security Lifecycle is differen
:PROPERTIES:
:ls-type: annotation
:hl-page: 62
:hl-color: yellow
:id: 63b30383-8b99-4236-b912-f94a86bf0dcb
:END:
* Locations: This can be illustrated by thinking of the lifecycle not as a single, linear operation, but as a series of smaller lifecycles running in different operating environments. At nearly any phase data can move into, out of, and between these environments.
:PROPERTIES:
:ls-type: annotation
:hl-page: 64
:hl-color: yellow
:id: 63b30740-e59d-438d-8fcc-7a71e55c640e
:END:
* Due to all the potential regulatory, contractual, and other jurisdictional issues, it is extremely important to understand both the logical and physical locations of data.
:PROPERTIES:
:ls-type: annotation
:hl-page: 64
:hl-color: yellow
:id: 63b30763-fd05-4650-90e3-330b63d20702
:END:
* Entitlements: When users know where the data lives and how it moves, they need to know who is accessing it and how. There are two factors here:
:PROPERTIES:
:ls-type: annotation
:hl-page: 64
:hl-color: yellow
:id: 63b30771-18da-49fa-bfe7-9150f9b8b26d
:END:
* Locations and Entitlements
:PROPERTIES:
:ls-type: annotation
:hl-page: 64
:hl-color: yellow
:id: 63b309b0-240a-49fa-a736-1ad10a57aec5
:END:
* Functions, Actors, and Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 65
:hl-color: yellow
:id: 63b309c8-a87e-40a8-9004-6eaf7f141497
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 66
:hl-color: yellow
:id: 63b30a34-ab22-4b50-92f7-ee121f0e7f84
:END:
* Management Plane and Business Continuity
:PROPERTIES:
:ls-type: annotation
:hl-page: 67
:hl-color: yellow
:id: 63b30b53-e5c4-4316-abfb-511d1e284a50
:END:
* gaining access to the management plane is like gaining unfettered access to your data center,
:PROPERTIES:
:ls-type: annotation
:hl-page: 67
:hl-color: yellow
:id: 63b30b75-8b94-443e-ab24-cd401c5bb33e
:END:
* In the end, this is an extension of the shared responsibility model discussed in Domain 1 and throughout this Guidance. The cloud management plane is responsible for managing the assets of the resource pool, while the cloud user is responsible for how they configure those assets
:PROPERTIES:
:ls-type: annotation
:hl-page: 67
:hl-color: yellow
:id: 63b30ba8-b24a-42fa-b3f6-39b07e2413fd
:END:
* Business Continuity and Disaster Recovery in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 68
:hl-color: yellow
:id: 63b30bbd-ff0a-4880-8fa2-7359ca5ee48f
:END:
* The three main aspects of BC/DR in the cloud are:
:PROPERTIES:
:ls-type: annotation
:hl-page: 68
:hl-color: yellow
:id: 63b30bcc-a93e-4fda-b204-b1e5d41c6b79
:END:
* Architect for Failure
:PROPERTIES:
:ls-type: annotation
:hl-page: 68
:hl-color: yellow
:id: 63b30c15-e180-4697-b3be-388f286d7153
:END:
* Cloud platforms can be incredibly resilient, but single cloud assets are typically less resilient than in the case of traditional infrastructure. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 68
:hl-color: yellow
:id: 63b30c29-cf19-446b-89a0-248209466020
:END:
* However, this means that cloud providers tend to offer options to improve resiliency, often beyond that which is attainable (for equivalent costs) in traditional infrastructure.
:PROPERTIES:
:ls-type: annotation
:hl-page: 68
:hl-color: yellow
:id: 63b30c3c-cb11-4e71-ad68-59931de39562
:END:
* But this extra resiliency is only achievable if you architect to leverage these capabilities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 69
:hl-color: yellow
:id: 63b30c4c-29dd-4a9f-a3b6-4d8b4ac1f993
:END:
* The ability to manage is higher with IaaS and much lower with SaaS, just like security. For SaaS, you rely on the cloud provider keeping the entire application service up. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 69
:hl-color: yellow
:id: 63b30c70-4523-488f-b11a-badf94c0535d
:END:
* Management Plane Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 69
:hl-color: yellow
:id: 63b30c83-229d-4eba-b983-a898c135e421
:END:
* For SaaS, the management plane is often the “admin” tab of the user interface and where you configure things like users, settings for the organization, etc.
:PROPERTIES:
:ls-type: annotation
:hl-page: 69
:hl-color: yellow
:id: 63b30c94-258c-423c-966f-3d0e90dd80a8
:END:
* The management plane controls and configures the metastructure (defined in Domain 1), and is also part of the metastructure itself. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 69
:hl-color: yellow
:id: 63b30ca5-d920-4870-874d-1254405827e7
:END:
* Accessing the Management Plane
:PROPERTIES:
:ls-type: annotation
:hl-page: 70
:hl-color: yellow
:id: 63b30cb5-8b6c-4e41-89da-9343d51f56ea
:END:
* Web consoles are managed by the provider. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 70
:hl-color: yellow
:id: 63b31601-60c0-4780-9f22-38ef19be9552
:END:
* Securing the Management Plane
:PROPERTIES:
:ls-type: annotation
:hl-page: 70
:hl-color: yellow
:id: 63b3161c-53e1-4e91-b8e0-164d2c611b42
:END:
* The specific options, configurations, and even concepts vary heavily between cloud providers and platforms. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 70
:hl-color: yellow
:id: 63b3162e-adb1-4280-8a1d-db36b284dc38
:END:
* Separate from the account-owner you can usually create super-admin accounts for individual admin use. Use these privileges sparingly; this should also be a smaller group since compromise or abuse of one of these accounts could allow someone to change or access essentially everything and anything.
:PROPERTIES:
:ls-type: annotation
:hl-page: 71
:hl-color: yellow
:id: 63b3163c-21d8-4f4d-9b98-5ff315ec7280
:END:
* Both providers and consumers should consistently only allow the least privilege required for users, applications, and other management plane usage.
:PROPERTIES:
:ls-type: annotation
:hl-page: 71
:hl-color: yellow
:id: 63b31655-05bc-4bb5-830c-7ce05c49df69
:END:
* All privileged user accounts should use multi-factor authentication (MFA). If possible, all cloud accounts (even individual user accounts) should use MFA.
:PROPERTIES:
:ls-type: annotation
:hl-page: 71
:hl-color: yellow
:id: 63b31667-426e-4f20-b90a-7479643716de
:END:
* Management Plane Security When Building/Providing a Cloud Service
:PROPERTIES:
:ls-type: annotation
:hl-page: 72
:hl-color: yellow
:id: 63b3167d-31a5-44ab-9a41-068ea606dbf5
:END:
* Delving into implementation specifics is beyond the scope of this Guidance, but at a high level there are five major facets to building and managing a secure management plane:
:PROPERTIES:
:ls-type: annotation
:hl-page: 72
:hl-color: yellow
:id: 63b31694-3609-402b-80a7-c73d19a4da17
:END:
* Business Continuity and Disaster Recovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 72
:hl-color: yellow
:id: 63b316c3-617e-47a4-829f-a3667222ff34
:END:
* Also similar to security, customers have more control and responsibility in IaaS, less in SaaS, with PaaS in the middle.
:PROPERTIES:
:ls-type: annotation
:hl-page: 72
:hl-color: yellow
:id: 63b316e0-a3e9-4356-990e-e1427b26f70a
:END:
* BC/DR must take a risk-based approach. Many BC options may be cost prohibitive in the cloud, but may also not be necessary.
:PROPERTIES:
:ls-type: annotation
:hl-page: 72
:hl-color: yellow
:id: 63b316e9-23ee-4443-8723-f3120227ec21
:END:
* For example, the odds of a major IaaS provider going out of business or changing their entire business model are low, but this isn’t all that uncommon for a smaller venture-backed SaaS provider.
:PROPERTIES:
:ls-type: annotation
:hl-page: 73
:hl-color: yellow
:id: 63b316fc-c7df-4e8f-9eb4-adf18df252d7
:END:
* Business Continuity Within the Cloud Provider
:PROPERTIES:
:ls-type: annotation
:hl-page: 73
:hl-color: yellow
:id: 63b3170a-2a2b-4a7d-8c40-2eb0acf25d40
:END:
* BC/DR must account for the entire logical stack:
:PROPERTIES:
:ls-type: annotation
:hl-page: 73
:hl-color: yellow
:id: 63b31781-2bde-4a52-a339-fe107191617e
:END:
* “Chaos Engineering” is often used to help build resilient cloud deployments. Since everything cloud is API-based, Chaos Engineering uses tools to selectively degrade portions of the cloud to continuously test business continuity.
:PROPERTIES:
:ls-type: annotation
:hl-page: 74
:hl-color: yellow
:id: 63b317b7-42ca-4d86-adde-e10f285c215c
:END:
* Understand PaaS limitations and lock-ins, and plan for the outage of a PaaS component. Platform services include a range of functions we used to manually implement in applications, everything from authentication systems to message queues and notifications. It isn’t unusual for modern applications to even integrate these kinds of services from multiple different cloud providers, creating an intricate web.
:PROPERTIES:
:ls-type: annotation
:hl-page: 74
:hl-color: yellow
:id: 63b317e3-0b7d-44d5-ba7e-25aab1fc142e
:END:
* Discussing availability of the component/service with your providers is reasonable. For example, the database service from your infrastructure provider may not share the same performance and availability as their virtual machine hosting.
:PROPERTIES:
:ls-type: annotation
:hl-page: 74
:hl-color: yellow
:id: 63b317f5-15b1-4e47-a975-0805e4ba9070
:END:
* Business Continuity for Loss of the Cloud Provider
:PROPERTIES:
:ls-type: annotation
:hl-page: 75
:hl-color: yellow
:id: 63b31802-c75b-42ad-ace7-349da0bf58af
:END:
* Depending on the history of your provider, and their internal availability capabilities, accepting this risk is often a legitimate option.
:PROPERTIES:
:ls-type: annotation
:hl-page: 75
:hl-color: yellow
:id: 63b3baf8-9930-45ec-a682-11d1ff49692b
:END:
* Be wary of selecting a secondary provider or service if said service may also be located or reliant on the same provider. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 75
:hl-color: yellow
:id: 63b3bb1e-9b86-4349-9ddc-a10c3b47ff4c
:END:
* Business Continuity For Private Cloud and Providers
:PROPERTIES:
:ls-type: annotation
:hl-page: 75
:hl-color: yellow
:id: 63b3bb3c-b83f-400c-9589-76dfd4e6ed7e
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 76
:hl-color: yellow
:id: 63b3bb5b-8e98-4732-82d2-6e460efea25f
:END:
* Infrastructure Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 77
:hl-color: yellow
:id: 63b3bba1-7720-4b13-bc35-5ef54fbf5b7f
:END:
* This domain also includes the fundamentals for private cloud computing. It does not include all the components of traditional data center security that are already well covered by existing standards and guidance.
:PROPERTIES:
:ls-type: annotation
:hl-page: 77
:hl-color: yellow
:id: 63b3bbd5-d325-48d6-ba60-ebef799d5029
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 77
:hl-color: yellow
:id: 63b3bbe9-e515-4c21-b5e8-5b523652023f
:END:
* Overview
:PROPERTIES:
:ls-type: annotation
:hl-page: 77
:hl-color: yellow
:id: 63b3bc1a-e6a9-4539-a69d-8a37f2243f5c
:END:
* Cloud Network Virtualization
:PROPERTIES:
:ls-type: annotation
:hl-page: 78
:hl-color: yellow
:id: 63b3bc37-0bd6-4afc-882d-4afbe13dd201
:END:
* There are two major categories of network virtualization commonly seen in cloud computing today:
:PROPERTIES:
:ls-type: annotation
:hl-page: 78
:hl-color: yellow
:id: 63b3bc77-302d-4d3d-be1f-d3456e381d8c
:END:
* VLANs are not designed for cloud-scale virtualization or security and shouldn’t be considered, on their own, an effective security control for isolating networks. They are also never a substitute for physical network segregation.
:PROPERTIES:
:ls-type: annotation
:hl-page: 79
:hl-color: yellow
:id: 63b3bcc8-e86a-4bda-89ec-496e854e8bb3
:END:
* SDN can offer much higher flexibility and isolation. For example, multiple segregated overlapping IP ranges for a virtual network on top of the same physical network. Implemented properly, and unlike standard VLANs, SDNs provide effective security isolation boundaries. SDNs also typically offer software definition of arbitrary IP ranges, allowing customers to better extend their existing networks into the cloud.
:PROPERTIES:
:ls-type: annotation
:hl-page: 79
:hl-color: yellow
:id: 63b3bd67-5a04-43a4-a1dc-ef9ef8c14a84
:END:
* How Security Changes With Cloud Networking
:PROPERTIES:
:ls-type: annotation
:hl-page: 79
:hl-color: yellow
:id: 63b3bd84-7c9e-4ee9-b8bb-e2c85510a9b7
:END:
* lack of direct management of the underlying physical network changes common network practices for the cloud user and provider.
:PROPERTIES:
:ls-type: annotation
:hl-page: 79
:hl-color: yellow
:id: 63b51601-38b6-4ecf-92e1-099393589cb5
:END:
* Traditional Network Intrusion Detection Systems, where communications between hosts are mirrored and inspected by the virtual or physical Intrusion Detection Systems will not be supported in cloud environments;
:PROPERTIES:
:ls-type: annotation
:hl-page: 79
:hl-color: yellow
:id: 63b5161f-be5e-4cc7-8915-7b3e133712b0
:END:
* Challenges of Virtual Appliances
:PROPERTIES:
:ls-type: annotation
:hl-page: 80
:hl-color: yellow
:id: 63b5163b-5f8b-41ef-963c-188e8a299fe3
:END:
* SDN Security Benefits
:PROPERTIES:
:ls-type: annotation
:hl-page: 80
:hl-color: yellow
:id: 63b51679-959c-4984-8088-1981f20b05ed
:END:
* Microsegmentation and the Software Defined Perimeter
:PROPERTIES:
:ls-type: annotation
:hl-page: 82
:hl-color: yellow
:id: 63b516f0-1d54-4c0e-858a-4ce7e2e11025
:END:
* Microsegmentation (also sometimes referred to as hypersegregation) leverages virtual network topologies to run more, smaller, and more isolated networks without incurring additional hardware costs that historically make such models prohibitive.
:PROPERTIES:
:ls-type: annotation
:hl-page: 82
:hl-color: yellow
:id: 63b51701-14ee-4c91-9a67-c551a3c2ceb0
:END:
* SDP includes three components:
:PROPERTIES:
:ls-type: annotation
:hl-page: 82
:hl-color: yellow
:id: 63b5171e-34cc-444a-84f1-de8c2dc50438
:END:
* Additional Considerations for Cloud Providers or Private Clouds
:PROPERTIES:
:ls-type: annotation
:hl-page: 83
:hl-color: yellow
:id: 63b51767-17ad-4a77-b5bb-325f8c1029c6
:END:
* It is absolutely critical to maintain segregation and isolation for the multitenant environment. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 83
:hl-color: yellow
:id: 63b51794-05da-40ff-a305-cc217f30f5da
:END:
* Hybrid Cloud Considerations
:PROPERTIES:
:ls-type: annotation
:hl-page: 83
:hl-color: yellow
:id: 63b517a6-a2f2-4f97-976c-fbc696c52ac6
:END:
* A hybrid connection shouldn’t effectively flatten the security of both networks. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 83
:hl-color: yellow
:id: 63b517ca-4039-4bd9-a552-f36fee4c9ee7
:END:
* For management and security reasons it is typically preferable to minimize hybrid connections.
:PROPERTIES:
:ls-type: annotation
:hl-page: 83
:hl-color: yellow
:id: 63b517d9-e4dc-40c5-b179-123710c85856
:END:
* One emerging architecture for hybrid cloud connectivity is “bastion” or “transit” virtual networks
:PROPERTIES:
:ls-type: annotation
:hl-page: 84
:hl-color: yellow
:id: 63b517ed-65ac-4c1f-8c7b-db18bd7f30da
:END:
* Cloud Compute and Workload Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 84
:hl-color: yellow
:id: 63b5180c-6d31-4fc0-8a9a-e832de814906
:END:
* A workload is a unit of processing, which can be in a virtual machine, a container, or other abstraction. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 84
:hl-color: yellow
:id: 63b51818-761f-487e-9bec-7821fb41417d
:END:
* here are multiple compute abstraction types, each with differing degrees of segregation and isolation:
:PROPERTIES:
:ls-type: annotation
:hl-page: 85
:hl-color: yellow
:id: 63b5182a-87f5-4da0-abaa-93730eafa736
:END:
* How Cloud Changes Workload Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 86
:hl-color: yellow
:id: 63b518ab-7eb1-4ad7-be01-04675822a084
:END:
* Cloud users rarely get to control where a workload physically runs, regardless of deployment model, although some platforms do support designating particular hardware pools or general locations to support availability, compliance, and other requirements.
:PROPERTIES:
:ls-type: annotation
:hl-page: 86
:hl-color: yellow
:id: 63b518cf-4000-48a1-84d8-99d81201403c
:END:
* Immutable Workloads Enable Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 86
:hl-color: yellow
:id: 63b518dc-10f1-4f34-ae8f-67ed03bb4691
:END:
* There are degrees of immutable. The pure definition is fully replacing running instances with a new image.
:PROPERTIES:
:ls-type: annotation
:hl-page: 86
:hl-color: yellow
:id: 63b518fb-6882-4687-983f-2e3284678f3f
:END:
* Immutable workloads enable significant security benefits:
:PROPERTIES:
:ls-type: annotation
:hl-page: 86
:hl-color: yellow
:id: 63b51918-a85a-4a34-acc3-9ffdfea2f474
:END:
* mmutable does add some requirements:
:PROPERTIES:
:ls-type: annotation
:hl-page: 87
:hl-color: yellow
:id: 63b5192e-608f-4304-a6b9-a04bdb288a1f
:END:
* The Impact of Cloud on Standard Workload Security Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 88
:hl-color: yellow
:id: 63b51948-ca58-4ecc-b7b3-760ba872871e
:END:
* Some standard workload controls aren’t as viable in cloud workloads (e.g. running antivirus inside some container types). 
:PROPERTIES:
:ls-type: annotation
:hl-page: 88
:hl-color: yellow
:id: 63b51963-648c-4c39-9c62-801c0a945ad3
:END:
* Changes to Workload Security Monitoring and Logging
:PROPERTIES:
:ls-type: annotation
:hl-page: 89
:hl-color: yellow
:id: 63b519ac-db63-4424-b445-46412ae5f591
:END:
* Security logging/monitoring is more complex in cloud computing:
:PROPERTIES:
:ls-type: annotation
:hl-page: 89
:hl-color: yellow
:id: 63b519b7-5917-46fc-a856-324439027638
:END:
* Changes to Vulnerability Assessment
:PROPERTIES:
:ls-type: annotation
:hl-page: 89
:hl-color: yellow
:id: 63b519ef-5420-4d68-8937-bd8a438e7bb4
:END:
* Cloud Storage Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 89
:hl-color: yellow
:id: 63b6423c-d60d-4743-ab87-b4253512711c
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 90
:hl-color: yellow
:id: 63b64254-b4f7-4428-8a06-dc19b34bb87c
:END:
* Virtualization and Containers
:PROPERTIES:
:ls-type: annotation
:hl-page: 91
:hl-color: yellow
:id: 63b6428c-b952-4296-8d78-2f96ff452782
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 91
:hl-color: yellow
:id: 63b64298-392f-4315-a214-88ea15e738e6
:END:
* Many security processes are designed with the expectation of physical control over the underlying infrastructure. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 92
:hl-color: yellow
:id: 63b642e0-9d0b-4c21-9d9f-90f5cac7cf48
:END:
* Security of the virtualization technology itself, e.g., securing a hypervisor.
:PROPERTIES:
:ls-type: annotation
:hl-page: 92
:hl-color: yellow
:id: 63b642f5-d43c-42c7-bb68-7b3da3031107
:END:
* Security controls for the virtual assets.
:PROPERTIES:
:ls-type: annotation
:hl-page: 92
:hl-color: yellow
:id: 63b642fd-411b-4af7-bdd2-bb392e9c22f0
:END:
* Major Virtualization Categories Relevant to Cloud Computing
:PROPERTIES:
:ls-type: annotation
:hl-page: 92
:hl-color: yellow
:id: 63b64321-1963-4f52-8302-173558649f7f
:END:
* Compute
:PROPERTIES:
:ls-type: annotation
:hl-page: 92
:hl-color: yellow
:id: 63b6432b-73e2-4520-a9cf-9673e8f8acfc
:END:
* Cloud Provider Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 93
:hl-color: yellow
:id: 63b64344-b3b0-4265-9bc9-7725d921ceb6
:END:
* Cloud User Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 93
:hl-color: yellow
:id: 63b64381-f667-4451-a123-e0f829eb5b05
:END:
* Network
:PROPERTIES:
:ls-type: annotation
:hl-page: 94
:hl-color: yellow
:id: 63b643f9-8ff2-4e26-aa66-3d73aba41f07
:END:
* Monitoring and Filtering
:PROPERTIES:
:ls-type: annotation
:hl-page: 95
:hl-color: yellow
:id: 63b64470-4d28-4cfb-8d43-47487290d640
:END:
* In particular, monitoring and filtering (including firewalls) change extensively due to the differences in how packets move around the virtual network. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 95
:hl-color: yellow
:id: 63b64494-7ace-4402-baea-4e51f85dab41
:END:
* With public cloud in particular, some communications between cloud services will occur on the Security Guidance v4.0 © Copyright 2021, Cloud Security Alliance. All rights reserved96 provider’s network; customer monitoring and filtering of that traffic isn’t possible
:PROPERTIES:
:ls-type: annotation
:hl-page: 95
:hl-color: yellow
:id: 63b644b2-47b3-4031-9067-32aafc30c543
:END:
* Management Infrastructure
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b644d3-92f7-4710-a215-9ad84b6b78e9
:END:
* Cloud Provider Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b644df-25af-4421-ae0c-7aa38bcae126
:END:
* The cloud provider is primarily responsible for building a secure network infrastructure and configuring it properly. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b64505-8ff2-4632-8e78-e0eaba360859
:END:
* The provider should disable packet sniffing or other metadata “leaks” that could expose data or configurations between tenants. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b6450f-db0a-4936-b265-25d2323f0a5d
:END:
* Cloud User Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b64535-c869-453d-ba5f-34a7dfe72dc7
:END:
* Cloud users are primarily responsible for properly configuring their deployment of the virtual network, especially any virtual firewalls.
:PROPERTIES:
:ls-type: annotation
:hl-page: 96
:hl-color: yellow
:id: 63b64549-b2ba-498a-9b99-13803582f458
:END:
* Cloud Overlay Networks
:PROPERTIES:
:ls-type: annotation
:hl-page: 97
:hl-color: yellow
:id: 63b6455f-ecbb-4d9a-a6a5-592c8e81ba7f
:END:
* Cloud overlay networks are a special kind of WAN virtualization technology for created networks that span multiple “base” networks. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 97
:hl-color: yellow
:id: 63b6456f-72d3-42e6-88d8-1df67608a500
:END:
* Storage
:PROPERTIES:
:ls-type: annotation
:hl-page: 97
:hl-color: yellow
:id: 63b64596-9962-49a3-8250-20f891c9c7f9
:END:
* this encryption doesn’t protect data in any virtualized layers; it only protects the data at physical storage. Depending on the type of storage the cloud provider may also (or instead) encrypt it at the virtualization layer, but this may not protect customer data from exposure to the cloud provider. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 97
:hl-color: yellow
:id: 63b645bc-49ff-4b84-bc7b-e8960e0ba9fd
:END:
* Containers
:PROPERTIES:
:ls-type: annotation
:hl-page: 97
:hl-color: yellow
:id: 63b645ca-cf21-44c4-9a4e-51c562a2c7b1
:END:
* Regardless of the technology platform, container security includes:
:PROPERTIES:
:ls-type: annotation
:hl-page: 98
:hl-color: yellow
:id: 63b645f1-76f1-4f18-915a-4e9aa9fcb2f9
:END:
* Containers don’t necessarily provide full security isolation, but they do provide task segregation.
:PROPERTIES:
:ls-type: annotation
:hl-page: 98
:hl-color: yellow
:id: 63b6462b-16cd-4fd8-999a-abd8257dbec3
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 99
:hl-color: yellow
:id: 63b6464b-56cc-48ad-b5f9-e82ef763dc87
:END:
* Incident Response
:PROPERTIES:
:ls-type: annotation
:hl-page: 101
:hl-color: yellow
:id: 63b6467c-3d1b-4ba7-841f-b379c8261975
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 101
:hl-color: yellow
:id: 63b6468a-747a-4f1c-b0e5-cccccee1ba37
:END:
* Incident Response Lifecycle
:PROPERTIES:
:ls-type: annotation
:hl-page: 102
:hl-color: yellow
:id: 63b646a6-fd45-40ee-85eb-5ff95ed91504
:END:
* How the Cloud Impacts IR
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b646d2-6570-40fd-833f-d888e85b75d4
:END:
* Preparation
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b646e0-21c4-49a1-aeb0-0bedc54f9abd
:END:
* Key questions include: What does your organization do? What is the cloud service provider (CSP) responsible for? Who are the points of contact? What are the response time expectations? What are the escalation procedures? Do you have out-of-band communication procedures (in case networks are impacted)? How do the hand-offs work? What data are you going to have access to?
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b646ff-89e0-474a-8a0a-ec447b3a124c
:END:
* Be sure to test the process with the CSP if possible. Validate that escalations and roles/ responsibilities are clear.
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b64729-4dfe-4996-b5a3-6b213634ed35
:END:
* IaaS/PaaS vs. SaaS: 
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b64772-c9d6-4a7f-92c7-720fa815e426
:END:
* “Cloud jump kit:” 
:PROPERTIES:
:ls-type: annotation
:hl-page: 103
:hl-color: yellow
:id: 63b64783-994d-4fb8-af37-53373a756e59
:END:
* Architect the cloud environment for faster detection, investigation, and response (containment and recoverability)
:PROPERTIES:
:ls-type: annotation
:hl-page: 104
:hl-color: yellow
:id: 63b6478d-a7f2-46c6-b163-6424082e3550
:END:
* Detection and Analysis
:PROPERTIES:
:ls-type: annotation
:hl-page: 104
:hl-color: yellow
:id: 63b64796-a0f2-4638-8b88-449798a5ad78
:END:
* Data sources for cloud incidents can be quite different from those used in incident response for traditional computing. There is significant overlap, such as system logs, but there are differences in terms of how data can be collected and in terms of new sources, such as feeds from the cloud management plane.
:PROPERTIES:
:ls-type: annotation
:hl-page: 104
:hl-color: yellow
:id: 63b78f46-5a8a-426c-ae34-d22b106c6b45
:END:
* One challenge in collecting information may be limited network visibility. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 105
:hl-color: yellow
:id: 63b78f5c-16d1-4ebc-bb1b-fdff1f81b8b6
:END:
* Forensics and investigative support will also need to adapt, beyond understanding changes to data sources.
:PROPERTIES:
:ls-type: annotation
:hl-page: 105
:hl-color: yellow
:id: 63b78f75-600f-4255-8753-b71562f8d820
:END:
* Always factor in what the CSP can provide and whether it meets chain of custody requirements. Not every incident will result in legal action, but it’s important to work with your legal team to understand the lines and where you could end up having chain of custody issues.
:PROPERTIES:
:ls-type: annotation
:hl-page: 105
:hl-color: yellow
:id: 63b78f84-c8f0-47ce-be2b-7aea9f6bb72c
:END:
* Containment, Eradication and Recovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 106
:hl-color: yellow
:id: 63b78fab-db5a-418a-800c-2f679b6c679a
:END:
* Always start by ensuring the cloud management plane/metastructure is free of an attacker.
:PROPERTIES:
:ls-type: annotation
:hl-page: 106
:hl-color: yellow
:id: 63b78fbf-436c-42ad-8a95-da5ea976b1ad
:END:
* Post-mortem
:PROPERTIES:
:ls-type: annotation
:hl-page: 106
:hl-color: yellow
:id: 63b78ff2-d38c-4b88-9eee-4ba2f31bb368
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 107
:hl-color: yellow
:id: 63b7900c-b62f-4ca1-85bc-22a918eef6bc
:END:
* Application Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 108
:hl-color: yellow
:id: 63b7903e-5399-458b-b6d8-d64daa579a9e
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 108
:hl-color: yellow
:id: 63b79049-3715-4e9d-8e92-707db24386f3
:END:
* Opportunities
:PROPERTIES:
:ls-type: annotation
:hl-page: 108
:hl-color: yellow
:id: 63b79073-f857-4239-a1ac-bfe9c205308e
:END:
* Challenges
:PROPERTIES:
:ls-type: annotation
:hl-page: 109
:hl-color: yellow
:id: 63b790d1-687f-43e5-84d2-c43ac2ddafc0
:END:
* Overview
:PROPERTIES:
:ls-type: annotation
:hl-page: 110
:hl-color: yellow
:id: 63b790f8-f431-4804-98c3-2a64f0dea8bb
:END:
* Introduction to the Secure Software Development Lifecycle and Cloud Computing
:PROPERTIES:
:ls-type: annotation
:hl-page: 110
:hl-color: yellow
:id: 63b791ec-8d85-4869-9416-9bd047f476a6
:END:
* Secure Design and Development
:PROPERTIES:
:ls-type: annotation
:hl-page: 112
:hl-color: yellow
:id: 63b792b6-bd14-4925-bc70-bd14f46e0ce2
:END:
* Security standards should include the initial entitlements for who is allowed to manage which services in the cloud provider, which is often independent of the actual application architecture. It should also include pre-approved tools, technologies, configurations, and even design patterns.
:PROPERTIES:
:ls-type: annotation
:hl-page: 112
:hl-color: yellow
:id: 63b79372-e2be-4fd2-8a68-316b85ce3cad
:END:
* We find that there are often significant security benefits to integrating security into the application architecture since there are opportunities to leverage the provider’s own security capabilities. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 112
:hl-color: yellow
:id: 63b793a4-0c2a-487c-be97-2855086e5696
:END:
* Security testing should be integrated into the deployment process and pipeline. Testing tends to span this and the Secure Deployment phase, but leans towards security unit tests, security functional tests, Static Application Security Testing (SAST), and Dynamic Application Security Testing(DAST
:PROPERTIES:
:ls-type: annotation
:hl-page: 113
:hl-color: yellow
:id: 63b793c3-9f87-4e8c-ab23-9a899c813993
:END:
* Secure Deployment
:PROPERTIES:
:ls-type: annotation
:hl-page: 113
:hl-color: yellow
:id: 63b79550-4ea6-40d2-8dc5-4727f79c6023
:END:
* There are multiple kinds of application security tests that could be potentially integrated into development and deployment:
:PROPERTIES:
:ls-type: annotation
:hl-page: 113
:hl-color: yellow
:id: 63b79561-0182-4de3-b0d4-82d9b8550ce3
:END:
* Impact on Vulnerability Assessment
:PROPERTIES:
:ls-type: annotation
:hl-page: 114
:hl-color: yellow
:id: 63b79589-6fd2-4b74-9343-31b3980972d1
:END:
* Impact on Penetration Testing
:PROPERTIES:
:ls-type: annotation
:hl-page: 114
:hl-color: yellow
:id: 63b7959e-224e-4976-a863-0b3302ebf5aa
:END:
* Deployment Pipeline Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 114
:hl-color: yellow
:id: 63b795b2-e0f6-4e60-beef-095f73d15ad8
:END:
* Impact of Infrastructure as Code and Immutable
:PROPERTIES:
:ls-type: annotation
:hl-page: 115
:hl-color: yellow
:id: 63b795c9-50cc-4dc3-8db4-55f4ee98e4e1
:END:
* The production environment can thus be locked down much more tightly than is normally possible in a non-cloud application deployment, where much of the infrastructure is configured manually to a specification. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 115
:hl-color: yellow
:id: 63b79608-42f0-413c-89bd-411a085ddc9b
:END:
* Secure Operations
:PROPERTIES:
:ls-type: annotation
:hl-page: 115
:hl-color: yellow
:id: 63b79623-0672-45e1-b0f6-7c0610342d6c
:END:
* his section contains additional guidance that more directly applies to applications:• The management plane for production environments should be much more tightly locked down than those for development. As previously mentioned, if the application directly accesses the management plane for the environment where it is hosted, then those privileges should be scoped to the least possible required. We recommend using multiple sets of credentials for each application service in order to further compartmentalize entitlements.• Even when using immutable infrastructure, the production environment should still be actively monitored for changes and deviations from approved baselines. This can and should be Security Guidance v4.0 © Copyright 2021, Cloud Security Alliance. All rights reserved116 automated through code (or tools) that make API calls to the cloud in order to regularly assess configuration state.
:PROPERTIES:
:ls-type: annotation
:hl-page: 115
:hl-color: yellow
:id: 63b79655-2a30-4bcb-a2b6-54c032de8b01
:END:
* How Cloud Impacts Application Design and Architectures
:PROPERTIES:
:ls-type: annotation
:hl-page: 116
:hl-color: yellow
:id: 63b79670-4b0b-4761-86b0-6697a8ad0f0c
:END:
* Additional Considerations for Cloud Providers
:PROPERTIES:
:ls-type: annotation
:hl-page: 117
:hl-color: yellow
:id: 63b79aca-0004-4ace-ab3b-faeb62e2a136
:END:
* Next, the serverless platforms may run on the provider’s network with communications to the consumer’s components through API or HTTPS traffic. This removes direct network attack paths, even if an attacker compromises a server or container. The attacker is limited to attempting API calls or HTTPS traffic and can’t port scan, identify other servers, or use other common techniques.
:PROPERTIES:
:ls-type: annotation
:hl-page: 117
:hl-color: yellow
:id: 63b79ae7-92ab-4eed-a812-5c7649863ca6
:END:
* The Rise and Role of DevOps
:PROPERTIES:
:ls-type: annotation
:hl-page: 117
:hl-color: yellow
:id: 63b79af8-e3af-4522-8876-e8e31c925e8a
:END:
* Security Implications and Advantages
:PROPERTIES:
:ls-type: annotation
:hl-page: 118
:hl-color: yellow
:id: 63b79b08-ac7f-4c9e-b75b-fb9122c5fbfa
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 118
:hl-color: yellow
:id: 63b79b2d-6cf3-44c3-aa89-235f5f6446ea
:END:
* Data Security and Encryption
:PROPERTIES:
:ls-type: annotation
:hl-page: 119
:hl-color: yellow
:id: 63b79b3f-62e0-4c34-8ff6-6fb2f0d85d14
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 119
:hl-color: yellow
:id: 63b79b4d-6bad-4213-80dc-ebe1be531943
:END:
* Overview
:PROPERTIES:
:ls-type: annotation
:hl-page: 119
:hl-color: yellow
:id: 63b79b66-f70a-4f9c-9fdb-2660f8e11647
:END:
* Data Security Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 119
:hl-color: yellow
:id: 63b79b6f-65e3-41db-8e96-35a43a0f3c95
:END:
* Cloud Data Storage Types
:PROPERTIES:
:ls-type: annotation
:hl-page: 120
:hl-color: yellow
:id: 63b79bb5-a053-4355-b21b-b5a45fbb65b1
:END:
* Most cloud platforms also use redundant, durable storage mechanisms that often utilize data dispersion (sometimes also known as data fragmentation of bit splitting). This process takes chunks of data, breaks them up, and then stores multiple copies on different physical storage to provide high durability. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 120
:hl-color: yellow
:id: 63b79bde-ae64-40fd-9ad6-a5042cacfe88
:END:
* Managing Data Migrations to the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 120
:hl-color: yellow
:id: 63b79be9-a02d-47dc-8dbf-7a18a095c84c
:END:
* Securing Cloud Data Transfers
:PROPERTIES:
:ls-type: annotation
:hl-page: 122
:hl-color: yellow
:id: 63b79c40-14d9-420d-9c56-d0d72ed3e4ba
:END:
* Securing Data in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 122
:hl-color: yellow
:id: 63b79c61-23ae-484c-9144-66efaa36250a
:END:
* Cloud Data Access Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 122
:hl-color: yellow
:id: 63b79c79-db71-438e-9b89-3901bf5ab98c
:END:
* Create an entitlement matrix based on platform-specific capabilities. An entitlement matrix documents which users, groups, and roles should access which resources and functions.
:PROPERTIES:
:ls-type: annotation
:hl-page: 122
:hl-color: yellow
:id: 63b79cae-6fd2-4bf8-a318-530d751d6114
:END:
* The depth of potential entitlements will vary greatly from technology to technology. Some databases may support row-level security, others little more than broad access. Some will allow you to tie entitlements to identity and enforcement mechanisms built into the cloud platform, while others rely completely on the storage platform itself merely running in virtual machines. It’s important to understand your options, map them out, and build your matrix. This applies to more than just file access, of course; it also applies to databases and all your cloud data stores.
:PROPERTIES:
:ls-type: annotation
:hl-page: 123
:hl-color: yellow
:id: 63b79cc4-c3be-4181-bf7d-a16cc00be498
:END:
* Storage (At-Rest) Encryption and Tokenization
:PROPERTIES:
:ls-type: annotation
:hl-page: 123
:hl-color: yellow
:id: 63b79ce5-1b5d-482f-b83f-109774c9874c
:END:
* Encryption and tokenization are two separate technologies. Encryption protects data by applying a mathematical algorithm that “scrambles” the data, which then can only be recovered by running it through an unscrambling (decryption) process with a corresponding key.
:PROPERTIES:
:ls-type: annotation
:hl-page: 123
:hl-color: yellow
:id: 63b79cfc-a556-48cd-ad49-ccf225c8a83c
:END:
* Tokenization is often used when the format of the data is important (e.g. replacing credit card numbers in an existing system that requires the same format text string). Format Preserving Encryption encrypts data with a key but also keeps the same structural format as tokenization, but it may not be as cryptographically secure due to the compromises.
:PROPERTIES:
:ls-type: annotation
:hl-page: 123
:hl-color: yellow
:id: 63b79d0c-91cb-45b3-80bf-4457ecf9e0f6
:END:
* IaaS Encryption
:PROPERTIES:
:ls-type: annotation
:hl-page: 124
:hl-color: yellow
:id: 63b79d38-1925-486b-bcda-e10db5cf5a05
:END:
* PaaS Encryption
:PROPERTIES:
:ls-type: annotation
:hl-page: 124
:hl-color: yellow
:id: 63b79d5e-19ec-445a-a6f0-974d6e1c64dd
:END:
* SaaS Encryption
:PROPERTIES:
:ls-type: annotation
:hl-page: 125
:hl-color: yellow
:id: 63b7a05a-5927-4349-808b-8dc1b9b684d4
:END:
* Key Management (Including Customer-Managed Keys)
:PROPERTIES:
:ls-type: annotation
:hl-page: 125
:hl-color: yellow
:id: 63b7a07b-6a57-4101-8d62-7e256fcb28e4
:END:
* A customer-managed key allows a cloud customer to manage their own encryption key while the provider manages the encryption engine. For example, using your own key to encrypt SaaS data within the SaaS platform.
:PROPERTIES:
:ls-type: annotation
:hl-page: 125
:hl-color: yellow
:id: 63b7a0c2-eece-4baf-a0fa-447030b367e0
:END:
* Some providers may require you to use a service within the provider to manage the key. Thus, although the key is customer-managed, it is still potentially available to provider. This doesn’t necessarily mean it is insecure
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a0e0-e866-4070-8ecc-adf64ecfde72
:END:
* Data Security Architectures
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a0f3-e379-45cb-a03b-88ded810ebbf
:END:
* Monitoring, Auditing, and Alerting
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a0fb-9986-4d58-bad4-61280f1342c6
:END:
* Additional Data Security Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a105-d7d2-42a9-a302-b71f25f5131d
:END:
* Cloud Platform/Provider-Specific Controls
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a110-8e71-4cee-a0ef-e586a25854f1
:END:
* Data Loss Prevention
:PROPERTIES:
:ls-type: annotation
:hl-page: 126
:hl-color: yellow
:id: 63b7a123-c279-4b1b-8cf7-778c8c93ffd7
:END:
* Enterprise Rights Managemen
:PROPERTIES:
:ls-type: annotation
:hl-page: 127
:hl-color: yellow
:id: 63b7a12a-0b53-4feb-b6b1-7c62c179ae23
:END:
* As with DLP, this is typically an employee security control that isn’t always as applicable in cloud. Since all Digital Rights Management (DRM)/Enterprise Rights Management (ERM) is based on encryption, existing tools may break cloud capabilities, especially in SaaS.
:PROPERTIES:
:ls-type: annotation
:hl-page: 127
:hl-color: yellow
:id: 63b7a139-5164-488a-bd96-33115ffe82a7
:END:
* The cloud platform may be able to enforce controls very similar to full DRM by using native capabilities. For example, user/device/view versus edit: a policy that only allows certain users to view a file in a web browser, while other users can download and/or edit the content. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 127
:hl-color: yellow
:id: 63b7a156-429a-4264-885d-8ecdb5473cde
:END:
* Data Masking and Test Data Generation
:PROPERTIES:
:ls-type: annotation
:hl-page: 127
:hl-color: yellow
:id: 63b7a165-8f4e-4f52-a6a1-0147990989d2
:END:
* Enforcing Lifecycle Management Security
:PROPERTIES:
:ls-type: annotation
:hl-page: 127
:hl-color: yellow
:id: 63b7a191-ee1e-4428-8f0c-a891fc7ecf42
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 128
:hl-color: yellow
:id: 63b7a1b2-48be-4831-a38f-206292bd483d
:END:
* Identity, Entitlement, and Access Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 129
:hl-color: yellow
:id: 63b7a1cb-cd4f-4d1c-bfdd-26b6cc732981
:END:
* Introduction
:PROPERTIES:
:ls-type: annotation
:hl-page: 129
:hl-color: yellow
:id: 63b7a1d2-dd38-4869-b141-6db439f945d9
:END:
* The key difference is the relationship between the cloud provider and the cloud user, even in private cloud. IAM can’t be managed solely by one or the other and thus a trust relationship, designation of responsibilities, and the technical mechanics to enable them are required.
:PROPERTIES:
:ls-type: annotation
:hl-page: 129
:hl-color: yellow
:id: 63b7a4d6-596a-480b-9d01-c36977fa46e0
:END:
* Cloud also tends to change faster, be more distributed (including across legal jurisdictional boundaries), add to the complexity of the management plane, 
:PROPERTIES:
:ls-type: annotation
:hl-page: 129
:hl-color: yellow
:id: 63b7a4e4-df0e-4fd2-ba01-8f1e2b7dffe4
:END:
* How IAM is Different in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 130
:hl-color: yellow
:id: 63b7a4ef-2035-4859-bc0f-a9173695be45
:END:
* Overview
:PROPERTIES:
:ls-type: annotation
:hl-page: 131
:hl-color: yellow
:id: 63b7a50b-83de-498c-81c0-0be186339619
:END:
* IAM Standards for Cloud Computing
:PROPERTIES:
:ls-type: annotation
:hl-page: 132
:hl-color: yellow
:id: 63b7a562-d434-4790-b7d6-6ff85f01ed37
:END:
* How Federated Identity Management Works
:PROPERTIES:
:ls-type: annotation
:hl-page: 133
:hl-color: yellow
:id: 63b7a5ae-e048-4891-a48e-08c6b824ac7a
:END:
* Identity protocols and standards do not represent a complete solution by themselves, but they are a means to an end.
:PROPERTIES:
:ls-type: annotation
:hl-page: 133
:hl-color: yellow
:id: 63b7a5e2-9330-428f-b5dc-50a957744ad0
:END:
* The essential concepts when choosing an identity protocol are:
:PROPERTIES:
:ls-type: annotation
:hl-page: 134
:hl-color: yellow
:id: 63b7a5f5-f9f2-4668-a179-bddf67471b6b
:END:
* Managing Users and Identities for Cloud Computing
:PROPERTIES:
:ls-type: annotation
:hl-page: 134
:hl-color: yellow
:id: 63b7a635-c010-4de6-884c-988ce9f0e66f
:END:
* Cloud providers need to nearly always support internal identities, identifiers, and attributes for users who directly access the service, while also supporting federation so that organizations don’t have to manually provision and manage every user in the provider’s system and issue everyone separate credentials.
:PROPERTIES:
:ls-type: annotation
:hl-page: 134
:hl-color: yellow
:id: 63b7a655-451c-4638-af01-b8584958bf07
:END:
* Cloud users need to decide where they want to manage their identities and which architectural models and technologies they want to support to integrate with cloud providers.
:PROPERTIES:
:ls-type: annotation
:hl-page: 134
:hl-color: yellow
:id: 63b7a65c-6cde-40a7-aaf3-c2f67547afc7
:END:
* Directly federating internal directory servers in the free-form model raises a few issues
:PROPERTIES:
:ls-type: annotation
:hl-page: 135
:hl-color: yellow
:id: 63b7a6aa-e642-4c6c-aafd-2d618923efef
:END:
* After determining the large-scale model, there are still process and architectural decisions required for any implementation
:PROPERTIES:
:ls-type: annotation
:hl-page: 136
:hl-color: yellow
:id: 63b7a6d0-53a9-4f4f-8aae-bdfa429b7fb2
:END:
* Authentication and Credentials
:PROPERTIES:
:ls-type: annotation
:hl-page: 136
:hl-color: yellow
:id: 63b7a701-3ba8-4b7f-870a-e367d309fe75
:END: