#+file-path: ./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf
#+file: [[./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf][csa_security_guidance_v4.0_1670814714973_0.pdf]]
#+title: hls__csa_security_guidance_v4.0_1670814714973_0

* It is a disruptive technology that has the potential to enhance collaboration, agility, scaling, and availability
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7c9a-29dc-4107-9d58-27bf8108c4f8
:END:
* Cloud computing is a model for enabling ubiquitous, convenient, on-demand network access to a shared pool of configurable computing resources (e.g., networks, servers, storage, applications, and services) that can be rapidly provisioned and released with minimal management effort or service provider interaction.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7cbb-07fa-4a3d-b567-7da388a371e8
:END:
* Paradigm for enabling network access to a scalable and elastic pool of shareable physical or virtual resources with self-service provisioning and administration on-demand.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7ccf-4903-459a-b713-e8ac5b8bfa86
:END:
* The key techniques to create a cloud are abstraction and orchestration. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7db7-979f-4dac-8d15-398d035bc4fe
:END:
* This is the difference between cloud computing and traditional virtualization; virtualization abstracts resources, but it typically lacks the orchestration to pool them together and deliver them to customers on demand, instead relying on manual processes.
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dc7-d4f5-4be2-a70f-925d9a7bbc80
:END:
* Clouds are multitenant by nature. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dd3-cd94-4c5a-96e6-fba937a263b5
:END:
* Essential Characteristics
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e07-fda3-4afa-94ef-48acdf4bcb43
:END:
* ISO/IEC 17788 lists six key characteristics, the first five of which are identical to the NIST characteristics. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e49-77cb-4660-b8af-1d7a93d8aedd
:END:
* Service Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e75-d7c4-4826-ab2e-b278eb4bd862
:END:
* ISO/IEC uses a more complex definition with a cloud capabilities type that maps closely to the SPI tiers (application, infrastructure, and platform capability types). It then expands into
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e9b-312b-4c2f-aa0f-1414ed075700
:END:
* Deployment Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7eba-2f61-489b-a116-f0c25c388f59
:END:
* Reference and Architecture Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7efc-dce0-4ba7-ae66-6b46a7acbc1f
:END:
* For an in-depth reference architectural model, we again recommend ISO/IEC 17789 and NIST 500-292, which complement the NIST definition model.
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7f09-afc6-4ab4-afa1-bcfdb11dabdb
:END:
* In most cases, those APIs are both remotely accessible and wrapped into a web-based user interface. This combination is the cloud management plane, since consumers use it to manage and configure the cloud resources, such as launching virtual machines (instances) or configuring virtual networks. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 14
:hl-color: yellow
:id: 639e7f53-dbe5-46f6-a57d-75328958966c
:END:
* PaaS adds an additional layer of integration with application development frameworks, middleware capabilities, and functions such as databases, messaging, and queuing.
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7f8f-3b45-45ca-bfa5-de1fc3fe4627
:END:
* One option, frequently seen in the real world and illustrated in our model, is to build a platform on top of IaaS. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fae-98ca-4de8-834c-743ecd0ae041
:END:
* Another example is an application deployment platform. T
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fc1-7ed3-47ce-829b-147492b98752
:END:
* Thus all SaaS tends to have an application/logic layer and data storage, with an API on top. Then there are one or more presentation layers, often including web browsers, mobile applications, and public API access.
:PROPERTIES:
:ls-type: annotation
:hl-page: 17
:hl-color: yellow
:id: 639e8002-f34a-4f75-a97a-5ad01695f9ba
:END:
* Logical Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e8018-9f5c-440d-bfbd-9a72f49066d1
:END:
* The key difference between cloud and traditional computing is the metastructure. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e807a-2d0e-4107-bfaa-b0b4b3b87601
:END:
* Another key difference is that, in cloud, you tend to double up on each layer. Infrastructure, for example, includes both the infrastructure used to create the cloud as well as the virtual infrastructure used and managed by the cloud user. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e808e-2424-4d16-9b53-b9c4870ee70b
:END:
* As we will discuss later this has profound implications on who is responsible for, and manages, security. These layers tend to map to different teams, disciplines, and technologies commonly found in IT organizations.
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e80b4-cb7a-4a24-b464-21fd736c0b4d
:END:
* All the traditional security domains remain, but the nature of risks, roles and responsibilities, and implementation of controls change, often dramatically.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ac7-6ee8-44d2-896e-e51c1dde3859
:END:
* Cloud Security and Compliance Scope and Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29af5-e72f-45e8-8327-4433fb5fa2a4
:END:
* At a high level, security responsibility maps to the degree of control any given actor has over the architecture stack:
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b40-d120-417b-a73b-aa340de34ccf
:END:
* Software as a Service: The cloud provider is responsible for nearly all security,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b7f-225b-4d32-aea3-ddcb98a90cd1
:END:
* Platform as a Service: The cloud provider is responsible for the security of the platform, while the consumer is responsible for everything they implement on the platform,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b95-368a-4707-8c05-910a1ea28525
:END:
* Infrastructure as a Service: Just like PaaS, the provider is responsible for foundational security, while the cloud user is responsible for everything they build on the infrastructure.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ba6-05f5-4293-96b9-3013922048af
:END:
* The most important security consideration is knowing exactly who is responsible for what in any given cloud projec
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bba-1e34-4627-a8a6-215756eb05a9
:END:
* This shared responsibility model directly correlates to two recommendations:• Cloud providers should clearly document their internal security controls and customer security features so the cloud user can make an informed decision. Providers should also properly design and implement those controls.• Cloud users should, for any given cloud project, build a responsibilities matrix to document who is implementing which controls and how. This should also align with any necessary compliance standards.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bd3-010d-41d1-9aec-1ad16148be1c
:END:
* • The Consensus Assessments Initiative Questionnaire (CAIQ). A standard template for cloud providers to document their security and compliance controls.• The Cloud Controls Matrix (CCM), which lists cloud security controls and maps them to multiple security and compliance standards. The CCM can also be used to document security responsibilities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29be8-86e6-4006-8567-b884aa109a7c
:END:
* Cloud security models are tools to help guide security decisions. The term “model” can be used a little nebulously, so for our purposes we break out the following types:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c1b-f38e-4471-b42c-8df3cfdacbed
:END:
* The CSA has reviewed and recommends the following models:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c46-53ed-448e-a6c6-7cb9b5636042
:END:
* there is a relatively straightforward, high-level process for managing cloud security:
:PROPERTIES:
:ls-type: annotation
:hl-page: 23
:hl-color: yellow
:id: 63a29c8f-df2e-4539-8e0c-91af8c2c8fcc
:END:
* Areas of Critical Focus
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29ce0-7ce5-45db-aaaa-1215edcf59e8
:END:
* Governing in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29d46-b49e-4af6-932d-45978a15d225
:END:
* Operating in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 25
:hl-color: yellow
:id: 63a29d54-776e-49ff-87b1-ee42348e8ae2
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 26
:hl-color: yellow
:id: 63a29de6-519e-48eb-81ac-aee67895a120
:END:
* Cloud Computing Concepts and Architectures
:PROPERTIES:
:ls-type: annotation
:hl-page: 7
:hl-color: yellow
:id: 63a29e36-db21-4a2d-923a-de4c8c06d71f
:END:
* Governance and Enterprise Risk Manag
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: blue
:id: 63a29e54-a150-4ad2-ab1e-02cae87b4862
:END:
* Governance and Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29eec-7c8e-4634-8dea-e4c55708329b
:END:
* For security professionals, cloud computing impacts four areas of governance and risk management:
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29f0d-b8d0-488d-aaa7-134dba06d5c0
:END:
* In a simplified hierarchy, information security is a tool of information risk management, which is a tool of enterprise risk management, which is a tool of governance. The four are all closely related but require individual focus, processes, and tools.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f54-371d-4b06-b6d3-24a6d2760f69
:END:
* Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f8a-f999-44bc-84fd-96226fe06188
:END:
* The primary issue to remember when governing cloud computing is that an organization can never outsource responsibility for governance, even when using external providers. This is always true, cloud or not, but is useful to keep in mind when navigating cloud computing’s concepts of shared responsibility models.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fa0-1b79-4142-8913-c0f3057216a6
:END:
* Cloud computing changes the responsibilities and mechanisms for implementing and managing governance. Responsibilities and mechanisms for governance are defined in the contract, as with Security Guidance v4.0 © Copyright 2021, Cloud Security Alliance. All rights reserved29 any business relationship
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fbb-8a95-4f89-99fb-0e12dda74092
:END:
* Tools of Cloud Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 29
:hl-color: yellow
:id: 63a29fd4-49dd-4566-9361-cab7fad8a7bb
:END:
* Assessments and audits should be based on existing standards (of which there are many). It’s critical to understand the scope, not just the standard used. Standards like the SSAE 16 have a defined scope, which includes both what is assessed (e.g. which of the provider’s services) as well as which controls are assessed
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a012-aeba-4f22-9a3c-7980e990b296
:END:
* Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a023-1d31-4335-92c2-a605eb24c9f7
:END:
* As with governance, the contract defines the roles and responsibilities for risk management between a cloud provider and a cloud customer. And, as with governance, you can never outsource your overall responsibility and accountability for risk management to an external provider.
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a045-f77e-4ebc-b3e4-93740df604a1
:END:
* Risk management in cloud is based on the shared responsibilities model (which we most often discuss in reference to security). The cloud provider accepts some responsibility for certain risks, and the cloud customer is responsible for anything beyond that. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a053-92a8-4472-af6b-85fe5309fa95
:END:
* Whereas governance is nearly exclusively focused on contracts, risk management can delve deeper into the technology and process capabilities of the provider, based on their documentation. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a07f-9ed1-4bb8-86eb-e1d638712195
:END:
* Risk tolerance is the amount of risk that the leadership and stakeholders of an organization are willing to accept.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a08b-1226-4d09-a32a-6f9f162dd304
:END:
* The Effects of Service Model and Deployment Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0a3-308f-45ca-9d7b-e02a0a873252
:END:
* In the majority of cases, SaaS presents the most critical example of the need for a negotiated contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0d9-ea14-4208-b0d0-9a99f88e68d2
:END:
* The likelihood of a fully negotiated contract is likely lower here than with either of the other service models. That’s because the core driver for most PaaS is to deliver a single capability with very high efficiency.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0f6-9783-4a39-b8ae-a982eef5f9c3
:END:
* Infrastructure as a Service represents the closest that Cloud comes to a traditional data center (or even a traditional outsourced managed data center), and the good news is that the vast majority of existing governance and risk management activities that organizations have already built and utilize are directly transferable. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a10f-8940-40d3-b2c6-f820b5561dc0
:END:
* Cloud customers have a reduced ability to govern operations in a public cloud since the provider is responsible for the management and governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a132-0dec-4914-96f7-9de2e4e70dc3
:END:
* The customers also often have reduced ability to negotiate contracts, which impacts how they extend their governance model into the cloud. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a144-c648-44ea-92ed-f9d5e48bd65a
:END:
* Public cloud isn’t the only model that impacts governance; even private cloud will have an effect. If an organization allows a third party to own and/or manage the private cloud (which is very common), this is similar to how governance affects any outsourced provider. There will be shared responsibilities with obligations that are defined in the contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a166-70c9-4a72-8b15-d99620ad842b
:END:
* When contemplating hybrid cloud environments, the governance strategy must consider the minimum common set of controls comprised of the Cloud Service Provider’s contract and the organization’s internal governance agreements. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a17f-8685-4935-a7f8-7bb804fa7cec
:END:
* Since community clouds are a shared platform with multiple organizations, but are not public, governance extends to the relationships with those members of the community, not just the provider and the customer. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a191-efd7-47ef-b305-abffda14a70b
:END:
* Cloud Risk Management Trade-Offs
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a1ab-b475-448a-b3cc-741045aacc81
:END:
* Cloud Risk Management Tools
:PROPERTIES:
:ls-type: annotation
:hl-page: 34
:hl-color: yellow
:id: 63a2a202-5b49-42a5-9dbc-79fb500d399c
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 35
:hl-color: yellow
:id: 63a2a23e-a885-460f-bc1a-0bf868508b55
:END:
* Legal Issues, Contracts and Electronic Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2ca-c1ab-41fb-908d-fa743bb1c83d
:END:
* Legal Frameworks Governing Data Protection and Privacy
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2e4-4fdf-45d2-8281-0cb967daf59f
:END:
* Under these laws, the data controller (typically the entity that has the primary relationship with an individual) is prohibited from collecting and processing personal data unless certain criteria are met. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a301-9c85-496b-9687-a99e5411b8b2
:END:
* the controller may collect and process data, according to the consent agreement. These laws define numerous obligations, such as confidentiality and security obligations, for the entities that access personal data. When entrusting a third party to process data on its behalf (a data processor), a data controller remains responsible for the collection and processing of that data. The data controller is required to ensure that any such third parties take adequate technical and organizational security measures to safeguard the data.
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a31e-34f1-40fb-9601-6beb0ab55d0e
:END:
* In many cases, the laws of different countries might apply concurrently, in accordance with the following:
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a32d-6cfa-4d76-a702-c408d1414549
:END: