#+file-path: ./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf
#+file: [[./../assets/csa_security_guidance_v4.0_1670814714973_0.pdf][csa_security_guidance_v4.0_1670814714973_0.pdf]]
#+title: hls__csa_security_guidance_v4.0_1670814714973_0

* It is a disruptive technology that has the potential to enhance collaboration, agility, scaling, and availability
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7c9a-29dc-4107-9d58-27bf8108c4f8
:END:
* Cloud computing is a model for enabling ubiquitous, convenient, on-demand network access to a shared pool of configurable computing resources (e.g., networks, servers, storage, applications, and services) that can be rapidly provisioned and released with minimal management effort or service provider interaction.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7cbb-07fa-4a3d-b567-7da388a371e8
:END:
* Paradigm for enabling network access to a scalable and elastic pool of shareable physical or virtual resources with self-service provisioning and administration on-demand.
:PROPERTIES:
:ls-type: annotation
:hl-page: 8
:hl-color: yellow
:id: 639e7ccf-4903-459a-b713-e8ac5b8bfa86
:END:
* The key techniques to create a cloud are abstraction and orchestration. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7db7-979f-4dac-8d15-398d035bc4fe
:END:
* This is the difference between cloud computing and traditional virtualization; virtualization abstracts resources, but it typically lacks the orchestration to pool them together and deliver them to customers on demand, instead relying on manual processes.
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dc7-d4f5-4be2-a70f-925d9a7bbc80
:END:
* Clouds are multitenant by nature. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 9
:hl-color: yellow
:id: 639e7dd3-cd94-4c5a-96e6-fba937a263b5
:END:
* Essential Characteristics
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e07-fda3-4afa-94ef-48acdf4bcb43
:END:
* ISO/IEC 17788 lists six key characteristics, the first five of which are identical to the NIST characteristics. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 10
:hl-color: yellow
:id: 639e7e49-77cb-4660-b8af-1d7a93d8aedd
:END:
* Service Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e75-d7c4-4826-ab2e-b278eb4bd862
:END:
* ISO/IEC uses a more complex definition with a cloud capabilities type that maps closely to the SPI tiers (application, infrastructure, and platform capability types). It then expands into
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7e9b-312b-4c2f-aa0f-1414ed075700
:END:
* Deployment Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 11
:hl-color: yellow
:id: 639e7eba-2f61-489b-a116-f0c25c388f59
:END:
* Reference and Architecture Models
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7efc-dce0-4ba7-ae66-6b46a7acbc1f
:END:
* For an in-depth reference architectural model, we again recommend ISO/IEC 17789 and NIST 500-292, which complement the NIST definition model.
:PROPERTIES:
:ls-type: annotation
:hl-page: 13
:hl-color: yellow
:id: 639e7f09-afc6-4ab4-afa1-bcfdb11dabdb
:END:
* In most cases, those APIs are both remotely accessible and wrapped into a web-based user interface. This combination is the cloud management plane, since consumers use it to manage and configure the cloud resources, such as launching virtual machines (instances) or configuring virtual networks. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 14
:hl-color: yellow
:id: 639e7f53-dbe5-46f6-a57d-75328958966c
:END:
* PaaS adds an additional layer of integration with application development frameworks, middleware capabilities, and functions such as databases, messaging, and queuing.
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7f8f-3b45-45ca-bfa5-de1fc3fe4627
:END:
* One option, frequently seen in the real world and illustrated in our model, is to build a platform on top of IaaS. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fae-98ca-4de8-834c-743ecd0ae041
:END:
* Another example is an application deployment platform. T
:PROPERTIES:
:ls-type: annotation
:hl-page: 16
:hl-color: yellow
:id: 639e7fc1-7ed3-47ce-829b-147492b98752
:END:
* Thus all SaaS tends to have an application/logic layer and data storage, with an API on top. Then there are one or more presentation layers, often including web browsers, mobile applications, and public API access.
:PROPERTIES:
:ls-type: annotation
:hl-page: 17
:hl-color: yellow
:id: 639e8002-f34a-4f75-a97a-5ad01695f9ba
:END:
* Logical Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e8018-9f5c-440d-bfbd-9a72f49066d1
:END:
* The key difference between cloud and traditional computing is the metastructure. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e807a-2d0e-4107-bfaa-b0b4b3b87601
:END:
* Another key difference is that, in cloud, you tend to double up on each layer. Infrastructure, for example, includes both the infrastructure used to create the cloud as well as the virtual infrastructure used and managed by the cloud user. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e808e-2424-4d16-9b53-b9c4870ee70b
:END:
* As we will discuss later this has profound implications on who is responsible for, and manages, security. These layers tend to map to different teams, disciplines, and technologies commonly found in IT organizations.
:PROPERTIES:
:ls-type: annotation
:hl-page: 19
:hl-color: yellow
:id: 639e80b4-cb7a-4a24-b464-21fd736c0b4d
:END:
* All the traditional security domains remain, but the nature of risks, roles and responsibilities, and implementation of controls change, often dramatically.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ac7-6ee8-44d2-896e-e51c1dde3859
:END:
* Cloud Security and Compliance Scope and Responsibilities
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29af5-e72f-45e8-8327-4433fb5fa2a4
:END:
* At a high level, security responsibility maps to the degree of control any given actor has over the architecture stack:
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b40-d120-417b-a73b-aa340de34ccf
:END:
* Software as a Service: The cloud provider is responsible for nearly all security,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b7f-225b-4d32-aea3-ddcb98a90cd1
:END:
* Platform as a Service: The cloud provider is responsible for the security of the platform, while the consumer is responsible for everything they implement on the platform,
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29b95-368a-4707-8c05-910a1ea28525
:END:
* Infrastructure as a Service: Just like PaaS, the provider is responsible for foundational security, while the cloud user is responsible for everything they build on the infrastructure.
:PROPERTIES:
:ls-type: annotation
:hl-page: 20
:hl-color: yellow
:id: 63a29ba6-05f5-4293-96b9-3013922048af
:END:
* The most important security consideration is knowing exactly who is responsible for what in any given cloud projec
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bba-1e34-4627-a8a6-215756eb05a9
:END:
* This shared responsibility model directly correlates to two recommendations:• Cloud providers should clearly document their internal security controls and customer security features so the cloud user can make an informed decision. Providers should also properly design and implement those controls.• Cloud users should, for any given cloud project, build a responsibilities matrix to document who is implementing which controls and how. This should also align with any necessary compliance standards.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29bd3-010d-41d1-9aec-1ad16148be1c
:END:
* • The Consensus Assessments Initiative Questionnaire (CAIQ). A standard template for cloud providers to document their security and compliance controls.• The Cloud Controls Matrix (CCM), which lists cloud security controls and maps them to multiple security and compliance standards. The CCM can also be used to document security responsibilities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 21
:hl-color: yellow
:id: 63a29be8-86e6-4006-8567-b884aa109a7c
:END:
* Cloud security models are tools to help guide security decisions. The term “model” can be used a little nebulously, so for our purposes we break out the following types:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c1b-f38e-4471-b42c-8df3cfdacbed
:END:
* The CSA has reviewed and recommends the following models:
:PROPERTIES:
:ls-type: annotation
:hl-page: 22
:hl-color: yellow
:id: 63a29c46-53ed-448e-a6c6-7cb9b5636042
:END:
* there is a relatively straightforward, high-level process for managing cloud security:
:PROPERTIES:
:ls-type: annotation
:hl-page: 23
:hl-color: yellow
:id: 63a29c8f-df2e-4539-8e0c-91af8c2c8fcc
:END:
* Areas of Critical Focus
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29ce0-7ce5-45db-aaaa-1215edcf59e8
:END:
* Governing in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 24
:hl-color: yellow
:id: 63a29d46-b49e-4af6-932d-45978a15d225
:END:
* Operating in the Cloud
:PROPERTIES:
:ls-type: annotation
:hl-page: 25
:hl-color: yellow
:id: 63a29d54-776e-49ff-87b1-ee42348e8ae2
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 26
:hl-color: yellow
:id: 63a29de6-519e-48eb-81ac-aee67895a120
:END:
* Cloud Computing Concepts and Architectures
:PROPERTIES:
:ls-type: annotation
:hl-page: 7
:hl-color: yellow
:id: 63a29e36-db21-4a2d-923a-de4c8c06d71f
:END:
* Governance and Enterprise Risk Manag
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: blue
:id: 63a29e54-a150-4ad2-ab1e-02cae87b4862
:END:
* Governance and Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29eec-7c8e-4634-8dea-e4c55708329b
:END:
* For security professionals, cloud computing impacts four areas of governance and risk management:
:PROPERTIES:
:ls-type: annotation
:hl-page: 27
:hl-color: yellow
:id: 63a29f0d-b8d0-488d-aaa7-134dba06d5c0
:END:
* In a simplified hierarchy, information security is a tool of information risk management, which is a tool of enterprise risk management, which is a tool of governance. The four are all closely related but require individual focus, processes, and tools.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f54-371d-4b06-b6d3-24a6d2760f69
:END:
* Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29f8a-f999-44bc-84fd-96226fe06188
:END:
* The primary issue to remember when governing cloud computing is that an organization can never outsource responsibility for governance, even when using external providers. This is always true, cloud or not, but is useful to keep in mind when navigating cloud computing’s concepts of shared responsibility models.
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fa0-1b79-4142-8913-c0f3057216a6
:END:
* Cloud computing changes the responsibilities and mechanisms for implementing and managing governance. Responsibilities and mechanisms for governance are defined in the contract, as with Security Guidance v4.0 © Copyright 2021, Cloud Security Alliance. All rights reserved29 any business relationship
:PROPERTIES:
:ls-type: annotation
:hl-page: 28
:hl-color: yellow
:id: 63a29fbb-8a95-4f89-99fb-0e12dda74092
:END:
* Tools of Cloud Governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 29
:hl-color: yellow
:id: 63a29fd4-49dd-4566-9361-cab7fad8a7bb
:END:
* Assessments and audits should be based on existing standards (of which there are many). It’s critical to understand the scope, not just the standard used. Standards like the SSAE 16 have a defined scope, which includes both what is assessed (e.g. which of the provider’s services) as well as which controls are assessed
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a012-aeba-4f22-9a3c-7980e990b296
:END:
* Enterprise Risk Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a023-1d31-4335-92c2-a605eb24c9f7
:END:
* As with governance, the contract defines the roles and responsibilities for risk management between a cloud provider and a cloud customer. And, as with governance, you can never outsource your overall responsibility and accountability for risk management to an external provider.
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a045-f77e-4ebc-b3e4-93740df604a1
:END:
* Risk management in cloud is based on the shared responsibilities model (which we most often discuss in reference to security). The cloud provider accepts some responsibility for certain risks, and the cloud customer is responsible for anything beyond that. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 30
:hl-color: yellow
:id: 63a2a053-92a8-4472-af6b-85fe5309fa95
:END:
* Whereas governance is nearly exclusively focused on contracts, risk management can delve deeper into the technology and process capabilities of the provider, based on their documentation. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a07f-9ed1-4bb8-86eb-e1d638712195
:END:
* Risk tolerance is the amount of risk that the leadership and stakeholders of an organization are willing to accept.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a08b-1226-4d09-a32a-6f9f162dd304
:END:
* The Effects of Service Model and Deployment Model
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0a3-308f-45ca-9d7b-e02a0a873252
:END:
* In the majority of cases, SaaS presents the most critical example of the need for a negotiated contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0d9-ea14-4208-b0d0-9a99f88e68d2
:END:
* The likelihood of a fully negotiated contract is likely lower here than with either of the other service models. That’s because the core driver for most PaaS is to deliver a single capability with very high efficiency.
:PROPERTIES:
:ls-type: annotation
:hl-page: 31
:hl-color: yellow
:id: 63a2a0f6-9783-4a39-b8ae-a982eef5f9c3
:END:
* Infrastructure as a Service represents the closest that Cloud comes to a traditional data center (or even a traditional outsourced managed data center), and the good news is that the vast majority of existing governance and risk management activities that organizations have already built and utilize are directly transferable. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a10f-8940-40d3-b2c6-f820b5561dc0
:END:
* Cloud customers have a reduced ability to govern operations in a public cloud since the provider is responsible for the management and governance
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a132-0dec-4914-96f7-9de2e4e70dc3
:END:
* The customers also often have reduced ability to negotiate contracts, which impacts how they extend their governance model into the cloud. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a144-c648-44ea-92ed-f9d5e48bd65a
:END:
* Public cloud isn’t the only model that impacts governance; even private cloud will have an effect. If an organization allows a third party to own and/or manage the private cloud (which is very common), this is similar to how governance affects any outsourced provider. There will be shared responsibilities with obligations that are defined in the contract.
:PROPERTIES:
:ls-type: annotation
:hl-page: 32
:hl-color: yellow
:id: 63a2a166-70c9-4a72-8b15-d99620ad842b
:END:
* When contemplating hybrid cloud environments, the governance strategy must consider the minimum common set of controls comprised of the Cloud Service Provider’s contract and the organization’s internal governance agreements. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a17f-8685-4935-a7f8-7bb804fa7cec
:END:
* Since community clouds are a shared platform with multiple organizations, but are not public, governance extends to the relationships with those members of the community, not just the provider and the customer. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a191-efd7-47ef-b305-abffda14a70b
:END:
* Cloud Risk Management Trade-Offs
:PROPERTIES:
:ls-type: annotation
:hl-page: 33
:hl-color: yellow
:id: 63a2a1ab-b475-448a-b3cc-741045aacc81
:END:
* Cloud Risk Management Tools
:PROPERTIES:
:ls-type: annotation
:hl-page: 34
:hl-color: yellow
:id: 63a2a202-5b49-42a5-9dbc-79fb500d399c
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 35
:hl-color: yellow
:id: 63a2a23e-a885-460f-bc1a-0bf868508b55
:END:
* Legal Issues, Contracts and Electronic Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2ca-c1ab-41fb-908d-fa743bb1c83d
:END:
* Legal Frameworks Governing Data Protection and Privacy
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a2e4-4fdf-45d2-8281-0cb967daf59f
:END:
* Under these laws, the data controller (typically the entity that has the primary relationship with an individual) is prohibited from collecting and processing personal data unless certain criteria are met. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 36
:hl-color: yellow
:id: 63a2a301-9c85-496b-9687-a99e5411b8b2
:END:
* the controller may collect and process data, according to the consent agreement. These laws define numerous obligations, such as confidentiality and security obligations, for the entities that access personal data. When entrusting a third party to process data on its behalf (a data processor), a data controller remains responsible for the collection and processing of that data. The data controller is required to ensure that any such third parties take adequate technical and organizational security measures to safeguard the data.
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a31e-34f1-40fb-9601-6beb0ab55d0e
:END:
* In many cases, the laws of different countries might apply concurrently, in accordance with the following:
:PROPERTIES:
:ls-type: annotation
:hl-page: 37
:hl-color: yellow
:id: 63a2a32d-6cfa-4d76-a702-c408d1414549
:END:
* Required Security Measures
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b758-8649-4f1a-b6b9-1e0a4650a2a7
:END:
* Restrictions to Cross-border Data Transfers
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b769-9c6f-4125-b27d-a9cca2f884da
:END:
* Many countries prohibit or restrict the transfer of information out of their borders. In most cases, the transfer is permitted only if the country to which the data is transferred offers an“adequate level of protection” 
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b792-ead3-49f6-8be9-8158174c1f8a
:END:
* Alternatively, the data importer and exporter may need to sign a contract ensuring the maintenance of privacy rights for data subjects.
:PROPERTIES:
:ls-type: annotation
:hl-page: 38
:hl-color: yellow
:id: 63a8b7a1-3a59-46e0-929e-5d17f746f558
:END:
* Regional Examples
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7b8-ca71-44c4-9ca0-2fe5d32ea64c
:END:
* he Privacy Act of 1988 (Privacy Act) 
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7d8-613b-4921-83c9-cbdf97bef50b
:END:
* Australian Consumer Law (ACL). 
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b7ed-e2fb-4d51-88ad-f10b3297c139
:END:
* May 2017, proposed Measures on the Security of Cross-Border Transfers of Personal Information and Important Data were published by the Chinese government and are currently being evaluated for potential implementation
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b812-45ad-4aef-bc29-f9c462be1daf
:END:
* 2017 Cyber Security Law
:PROPERTIES:
:ls-type: annotation
:hl-page: 39
:hl-color: yellow
:id: 63a8b81e-d4f3-4fd1-8671-7059d9358bae
:END:
* The Cyber Security Law imposes a series of security obligations to operators of critical information infrastructure, including internal organization, training, data backup; emergency response requirements, security inspections and annual assessments of cyber security risks; and reporting to relevant authorities.
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b846-9077-4006-89ce-fdf7020be514
:END:
* During the second quarter of 2017, China issued Draft Regulations on Cross Border Data Transfers to supplement the Cyber Security Law. These regulations would go beyond the working of the Cyber Security Law, and expand its scope.
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b855-01c1-4de1-8285-6efd80399564
:END:
* Act on the Protection of Personal Information (APPI
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b86a-c23c-4f3e-a510-cef1fd6628fd
:END:
* Profession-specific laws, such as the Medical Practitioners’ Act; the Act on Public Health Nurses, Midwives and Nurses; and the Pharmacist Act, require registered health professionals to maintain the confidentiality of patient information
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b884-be4d-411d-bb50-1051627a2bc0
:END:
* September 2017, amendments to the APPI law will limit the ability to transfer personal data to third parties, with prior consent of the data subject generally being required to transfer data to a third party
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8b890-ea8d-4e60-b3e5-7e920a5872bb
:END:
* the most important aspect of the Russian legal framework regarding the handling of personal information is its data localization law. Since September 2015, companies are required to store personal data of Russian citizens within Russia
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8c49e-2f8b-49ea-a9f8-8c02aaf9ed01
:END:
* Roskomnadzor, the Russian Data Protection regulator, has commenced enforcement of the law and has already blocked access to one foreign social network, which did not have a physical presence in Russia, but operated a Russian language version of its website
:PROPERTIES:
:ls-type: annotation
:hl-page: 40
:hl-color: yellow
:id: 63a8c4b0-2abe-47ee-8117-2d502260bcfa
:END:
* The European Union (EU) adopted the General Data Protection Regulation (GDPR) in 2016, which is binding on all EU member states, as well as members of the European Economic Area (EEA). The GDPR will become enforceable as of May 25, 2018. On that date, Directive 95/46/EC on the Protection of Personal Data, which had been the legal basis of the provisions of the national data protection laws of all EU and EEA member states, will be repealed.
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4c8-8695-41b1-b9a8-6a24b5cfd9cd
:END:
* important document governing aspects of the protection of personal data in the EU/EEA is Directive 2002/58/EC on Privacy and Electronic Communications
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4d7-31c0-4ccd-b441-6f1f728d05c0
:END:
* the Network Information Security Directive (NIS Directive) is paving the way to more stringent security requirements. Adopted in 2016, the NIS Directive requires EU/EEA member states to implement new information security laws for the protection of critical infrastructure and essential services by May 2018
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4e8-ccb8-4592-b42c-44d04de46bdf
:END:
* General Data Protection Regulation (GDPR)
:PROPERTIES:
:ls-type: annotation
:hl-page: 41
:hl-color: yellow
:id: 63a8c4f4-37ac-4cc8-a89c-750a07105e65
:END:
* Network Information Security Directive (NIS Directive)
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8c500-0a69-4f05-b87b-086488e4527a
:END:
* he NIS Directive establishes a framework to enable networks and information systems to resist, at a given level of confidence, actions that compromise the availability, authenticity, integrity, or confidentiality of stored, transmitted, or processed data, or the related services that are offered by or accessible through those networks and information systems
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8e0a2-2a84-48aa-a162-594a7316e0fd
:END:
* The requirements to be implemented into national laws include the following:
:PROPERTIES:
:ls-type: annotation
:hl-page: 42
:hl-color: yellow
:id: 63a8e0ca-342c-4277-a253-bfec3b1f8f56
:END:
* Due to its sectoral approach, the United States has hundreds of federal, state and local regulations,
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e111-087f-4347-b687-f8e01817bfde
:END:
* extensive requirements under Massachusetts’“Standards for the Protection of Personal Information of Residents of the Commonwealth,” 
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e15b-9fa0-44e6-b266-901daa86af5a
:END:
* a small number of state laws reference other specific standards (such as the Payment Card Industry Data Security Standard, PCI-DSS
:PROPERTIES:
:ls-type: annotation
:hl-page: 44
:hl-color: yellow
:id: 63a8e16b-fe82-46f6-a53f-9b47b62d6f48
:END:
* Contracts and Provider Selection
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e1bd-661c-47e4-aaa5-aad06fdac86e
:END:
* Even if a specific activity is not regulated, cloud customers may have a contractual obligation to protect the personal information of their own clients, contacts or employees
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e229-7a43-46c5-bd84-3beeb6444f6c
:END:
* This obligation may stem, for example, from the Terms and Conditions and Privacy Statement
:PROPERTIES:
:ls-type: annotation
:hl-page: 45
:hl-color: yellow
:id: 63a8e237-fe1d-4f32-9a69-746e4ea86453
:END:
* It is therefore prudent, and may be required by law or regulation, that the data custodian and the cloud provider enter into a formal written agreement that clearly defines the roles, the expectations of the parties, and the allocation of the many responsibilities that are attached to the data at stake.
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e25e-1b73-4383-b7f0-2a4a625d3781
:END:
* Internal Due Diligence
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e269-6a9c-4d57-a8e4-1110d2a7e51f
:END:
* Before entering into a cloud computing arrangement, both the cloud service vendor and the cloud customer should evaluate respective practices, needs and restrictions to identify relevant legal barriers and compliance requirements.
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e2c2-53fa-4607-8b3f-6faae86aaabf
:END:
* If the company, or potential cloud customer, has signed a confidentiality agreement to protect personal information or trade secrets, this agreement probably prohibits hiring a subcontractor without prior permission of the data owner. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 46
:hl-color: yellow
:id: 63a8e2d9-d025-445f-9fe1-afa4732f63c0
:END:
* Monitoring, Testing, and Updating
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e2fc-418e-4db5-8e78-f768051b2b08
:END:
* External Due Diligence
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e30f-5ff9-4995-8ee1-8e35612672f6
:END:
* Thus, depending on the nature of the proposed project, the due diligence may involve evaluating the nature and completeness of the services provided, the reputation for quality or stability of the service, the availability of a certain level of support or maintenance, the responsiveness of customer service, the speed of the network, and the location of the data centers.
:PROPERTIES:
:ls-type: annotation
:hl-page: 47
:hl-color: yellow
:id: 63a8e336-43bb-441a-ba1c-0870bd32e852
:END:
* Reviewing all terms and conditions of the cloud services agreement (including all annexes, schedules and appendices) is good due diligence for any new project.
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e34f-1950-4589-af05-f0ff06ca6677
:END:
* Contract Negotiations
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e35b-3fb0-48a2-b750-fa6020f26160
:END:
* Reliance on Third-Party Audits and Attestations
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e650-a41c-4dd3-9d86-32cd259a9554
:END:
* In cloud computing, third-party audits and attestations are frequently used to assure compliance with aspects of the cloud provider’s infrastructure, allowing a customer to build their own compliant services on top of the cloud platform.
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e666-a395-4369-b2d2-5ee0d7b7e49c
:END:
* Electronic Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e67f-94d8-414d-bbf8-1194689d87c2
:END:
* In recent years, many litigants have deleted, lost or modified evidence that was detrimental to their case. In these cases, the Federal Rules of Civil Procedure allow, among other penalties, money to be awarded to the side not responsible for the destruction; 
:PROPERTIES:
:ls-type: annotation
:hl-page: 48
:hl-color: yellow
:id: 63a8e69b-899a-4d52-a083-fb001d479e1c
:END:
* Possession, Custody and Control
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6b0-a9aa-4b05-8dff-8f34992d917c
:END:
* Relevant Cloud Applications and Environment
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6c6-e4d8-4d1b-9386-baea091eaf6a
:END:
* Searchability and E-Discovery Tools
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6d7-51ed-44cf-939f-6e0ee3397848
:END:
* Preservation
:PROPERTIES:
:ls-type: annotation
:hl-page: 49
:hl-color: yellow
:id: 63a8e6f6-477c-4e85-a269-d43b4dfd6e74
:END:
* European Union, information preservation is governed under Directive 2006/24/EC of the European Parliament and of the Council of 15 March 2006.
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e719-6bb3-4d37-a7a2-84bd4c9525b4
:END:
* Japan, South Korea and Singapore have similar data protection initiatives. In South America, Brazil and Argentina have the Azeredo Bill and the Argentina Data Retention Law of2004, Law No. 25.873, respectively.
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e722-e67c-42f7-8429-f649d25cd2dc
:END:
* Data Retention Laws and Record Keeping Obligations
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e72e-45bc-4967-b2c0-df5d100c8097
:END:
* Costs and Storage: Preservation can require that large volumes of data be retained for extended periods. Customers should consider these questions and determine the risk tolerated before moving to the cloud:
:PROPERTIES:
:ls-type: annotation
:hl-page: 50
:hl-color: yellow
:id: 63a8e746-7f00-4ed3-b008-89d77fcdf4e6
:END:
* Collection
:PROPERTIES:
:ls-type: annotation
:hl-page: 51
:hl-color: yellow
:id: 63a8e773-7fc1-46cb-8ad5-d50f41d1f48e
:END:
* Because of the potential lack of administrative control a client has over its data in the cloud, collection from the cloud can be more difficult, more time-consuming and more expensive than from behind a client’s firewall. 
:PROPERTIES:
:ls-type: annotation
:hl-page: 51
:hl-color: yellow
:id: 63a8e78e-c397-4e71-aa7e-6b6bf377d388
:END:
* Direct Access
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e860-27bd-4376-a9be-d97c2f8c665e
:END:
* Native Production
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e879-5d37-4a64-87e9-8b23078956b2
:END:
* Authenticatio
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e890-a679-475c-aec9-cf61678e5434
:END:
* Cooperation Between Provider and Client in E-Discovery
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e8a6-b2ca-4218-a617-fff05075c1dd
:END:
* Response to a Subpoena or Search Warrant
:PROPERTIES:
:ls-type: annotation
:hl-page: 52
:hl-color: yellow
:id: 63a8e8c2-9745-42e2-86d1-9f186f753087
:END:
* More Information
:PROPERTIES:
:ls-type: annotation
:hl-page: 53
:hl-color: yellow
:id: 63a8e8f9-f71a-4a6d-9d96-c37fbafc6789
:END:
* Recommendations
:PROPERTIES:
:ls-type: annotation
:hl-page: 53
:hl-color: yellow
:id: 63a8e90e-85b9-4d11-b23e-458cd5fe1252
:END:
* Compliance and Audit Management
:PROPERTIES:
:ls-type: annotation
:hl-page: 54
:hl-color: yellow
:id: 63a8e927-8c29-4f59-a7a1-d6dbe32cb126
:END: